var ficBooks = [
    {
        bookTitle: "Dune",
        bookAuthor: "Frank Herbert",
        bookCover: "images/dune.jpg",
        bookRating: 5,
        bookPrice: 10.99,
        ISBN: 9780441013593,
        publisher: "Penguin Publishing Group",
        publicationDate: "08/02/2005",
        pages: 704,
        productDimensions: "5.84(w) x 8.92(h) x 1.12(d)",
        overview: "A masterpiece of the Science Fiction genre, Dune laid the foundation for many of the epics that followed. Frank Herbert addresses overarching themes of family politics, religion, environment and the all-encompassing temptation of power, all set against the backdrop of a futuristic civilization that, at times, can be unflinchingly prophetic. You will taste the sand in your mouth and soon be hungry for the next installment. • DUNE: PART TWO • THE MAJOR MOTION PICTURE Directed by Denis Villeneuve, screenplay by Denis Villeneuve and Jon Spaihts, based on the novel Dune by Frank Herbert • Starring Timothée Chalamet, Zendaya, Rebecca Ferguson, Josh Brolin, Austin Butler, Florence Pugh, Dave Bautista, Christopher Walken, Stephen McKinley Henderson, Léa Seydoux, with Stellan Skarsgård, with Charlotte Rampling, and Javier Bardem Frank Herbert’s classic masterpiece—a triumph of the imagination and one of the bestselling science fiction novels of all time. Set on the desert planet Arrakis, Dune is the story of Paul Atreides—who would become known as Muad'Dib—and of a great family's ambition to bring to fruition humankind's most ancient and unattainable dream. A stunning blend of adventure and mysticism, environmentalism and politics, Dune won the first Nebula Award, shared the Hugo Award, and formed the basis of what is undoubtedly the grandest epic in science fiction.",
        tableOfContent: ["DuneBook I. Dune", "Book II. Muad'dib", "Book III. The Prophet", "Appendix I: The Ecology of Dune", "Appendix II: The Religion of Dune", "Appendix III: Report on Bene Gesserit", "Motives and Purposes", "Appendix IV: The Almanaken-Ashraf", "(Selected Excerpts of the Noble Houses)"],
    },
    {
        bookTitle: "The Odyssey",
        bookAuthor: "Homer",
        bookCover: "images/the odyssey.jpg",
        bookRating: 5,
        bookPrice: 12,
        ISBN: 9780140268867,
        publisher: "Penguin Classics",
        publicationDate: "11/01/1997",
        pages: 560,
        productDimensions: "5.10(w) x 7.80(h) x 1.10(d)",
        overview: "The Odyssey is one of the greatest works of classical literature, attributed to the ancient Greek poet Homer. It tells the epic tale of Odysseus's journey home after the Trojan War, filled with adventure, danger, and the enduring power of human resilience.",
        tableOfContent: ["Book I: Athena Inspires the Prince", "Book II: Telemachus Sets Sail", "Book III: King Nestor Remembers", "Book IV: The King and Queen of Sparta", "Book V: Odysseus - Nymph and Shipwreck", "Book VI: The Princess and the Stranger"],
    },
    {
        bookTitle: "The Hunger Games",
        bookAuthor: "Suzanne Collins",
        bookCover: "images/The hunger Games.jpg",
        bookRating: 4,
        bookPrice: 6.99,
        ISBN: 9780439023481,
        publisher: "Scholastic Press",
        publicationDate: "09/14/2008",
        pages: 384,
        productDimensions: "5.50(w) x 8.25(h) x 1.00(d)",
        overview: "In a dystopian future, Katniss Everdeen volunteers to take her sister's place in the Hunger Games, a televised fight to the death. Suzanne Collins's gripping novel explores themes of survival, sacrifice, and rebellion.",
        tableOfContent: ["Part I: The Tributes", "Part II: The Games", "Part III: The Victor"],
    },
    {
        bookTitle: "The Girl With The Dragon Tattoo",
        bookAuthor: "Stieg Larsson",
        bookCover: "images/the girl with the dragon tattoo.jpg",
        bookRating: 4,
        bookPrice: 7.99,
        ISBN: 9780307949486,
        publisher: "Vintage Crime/Black Lizard",
        publicationDate: "11/22/2011",
        pages: 672,
        productDimensions: "5.20(w) x 8.00(h) x 1.30(d)",
        overview: "A spellbinding mystery thriller, The Girl With The Dragon Tattoo follows journalist Mikael Blomkvist and hacker Lisbeth Salander as they unravel a decades-old disappearance in Sweden.",
        tableOfContent: ["Prologue", "Part 1: Incentive", "Part 2: Consequence Analysis", "Part 3: Mergers and Acquisitions"],
    },
    {
        bookTitle: "Sunrise on the Reaping (A Hunger Games Novel)",
        bookAuthor: "Suzanne Collins",
        bookCover: "images/booksCovers/Sunrise on the Reaping (A Hunger Games Novel).jpg",
        bookRating: 5,
        bookPrice: 22.39,
        ISBN: 9781546171461        ,
        publisher: "Scholastic, Inc.",
        publicationDate: "03/18/2025",
        pages: 400,
        productDimensions: "5.80(w) x 8.30(h) x 1.50(d)",
        overview: "The Fiftieth Annual Hunger Games are about to begin. Who will be tribute? Who will live and die? Return to Panem for more pulse-pounding action than ever before. Oh, and may the odds be ever in your favor.\n\nThe phenomenal fifth book in the Hunger Games series!\nWhen you’ve been set up to lose everything you love, what is there left to fight for?\n\nAs the day dawns on the fiftieth annual Hunger Games, fear grips the districts of Panem. This year, in honor of the Quarter Quell, twice as many tributes will be taken from their homes.\n\nBack in District 12, Haymitch Abernathy is trying not to think too hard about his chances. All he cares about is making it through the day and being with the girl he loves.\n\nWhen Haymitch’s name is called, he can feel all his dreams break. He’s torn from his family and his love, shuttled to the Capitol with the three other District 12 tributes: a young friend who’s nearly a sister to him, a compulsive oddsmaker, and the most stuck-up girl in town. As the Games begin, Haymitch understands he’s been set up to fail. But there’s something in him that wants to fight . . . and have that fight reverberate far beyond the deadly arena.",
        tableOfContent: ["#", "#", "#", "#"],
    },
    {
        bookTitle: "Great Big Beautiful Life (B&N Exclusive Edition)",
        bookAuthor: "Emily Henry",
        bookCover: "images/booksCovers/Great Big Beautiful Life (B&N Exclusive Edition).jpg",
        bookRating: 5,
        bookPrice: 24.00,
        ISBN: 9780593955628,
        publisher: "Penguin Publishing Group",
        publicationDate: "04/22/2025",
        pages: 384,
        productDimensions: "6.30(w) x 9.20(h) x 1.10(d)",
        overview:"An elusive heiress, a love story and a mystery. Cathartic, romantic, tragic and charming, Emily Henry told her readers this book challenged her like no other. Grab an extra copy — you’ll want to share it with everyone you know.\n\nThis Barnes and Noble Exclusive edition includes a special colorway, beautiful endpapers, and an alternate case color with an exclusive foil-stamped quote.\nTwo writers compete for the chance to tell the larger-than-life story of a woman with more than a couple of plot twists up her sleeve in this dazzling and sweeping new novel from Emily Henry.\n\nAlice Scott is an eternal optimist still dreaming of her big writing break. Hayden Anderson is a Pulitzer-prize winning human thundercloud. And they’re both on balmy Little Crescent Island for the same reason: To write the biography of a woman no one has seen in years--or at least to meet with the octogenarian who claims to be the Margaret Ives. Tragic heiress, former tabloid princess, and daughter of one of the most storied (and scandalous) families of the 20th Century.\n\nWhen Margaret invites them both for a one-month trial period, after which she’ll choose the person who’ll tell her story, there are three things keeping Alice’s head in the game.\n\nOne: Alice genuinely likes people, which means people usually like Alice—and she has a whole month to win the legendary woman over.\n\nTwo: She’s ready for this job and the chance to impress her perennially unimpressed family with a Serious Publication.\n\nThree: Hayden Anderson, who should have no reason to be concerned about losing this book, is glowering at her in a shaken-to-the core way that suggests he sees her as competition.\n\nBut the problem is, Margaret is only giving each of them pieces of her story. Pieces they can’t swap to put together because of an ironclad NDA and an inconvenient yearning pulsing between them every time they’re in the same room.\n\nAnd it’s becoming abundantly clear that their story—just like the tale Margaret’s spinning—could be a mystery, tragedy, or love ballad…depending on who’s telling it.",
        tableOfContent: ["#", "#", "#", "#"],
    },
    {
        bookTitle: "Harry Potter And The Sorcerer's Stone",
        bookAuthor: "J.K. Rowling",
        bookCover: "images/Harry potter and the sorcerer's stone.jpg",
        bookRating: 5,
        bookPrice: 5,
        ISBN: 9780590353427,
        publisher: "Scholastic Inc.",
        publicationDate: "09/01/1998",
        pages: 320,
        productDimensions: "5.50(w) x 8.25(h) x 0.90(d)",
        overview: "The first book in J.K. Rowling's beloved Harry Potter series introduces readers to the magical world of Hogwarts and the young wizard Harry Potter as he discovers his destiny.",
        tableOfContent: ["Chapter 1: The Boy Who Lived", "Chapter 2: The Vanishing Glass", "Chapter 3: The Letters from No One", "Chapter 4: The Keeper of the Keys"],
    },
    {
        bookTitle: "Jurassik Park",
        bookAuthor: "Michael Crichton",
        bookCover: "images/Jurassik Park.jpg",
        bookRating: 4,
        bookPrice: 8,
        ISBN: 9780345538987,
        publisher: "Ballantine Books",
        publicationDate: "11/20/1990",
        pages: 416,
        productDimensions: "5.50(w) x 8.20(h) x 1.10(d)",
        overview: "Michael Crichton's Jurassic Park is a thrilling science fiction novel about a theme park filled with genetically engineered dinosaurs that goes disastrously wrong.",
        tableOfContent: ["Introduction", "Part 1: The Island", "Part 2: The Tour", "Part 3: The Chaos", "Part 4: The Control"],
    },
    {
        bookTitle: "The Hobbit, or There and Back Again",
        bookAuthor: "J.R.R. Tolkien",
        bookCover: "images/The hobbit.jpg",
        bookRating: 4,
        bookPrice: 4.99,
        ISBN: 9780547928227,
        publisher: "Mariner Books",
        publicationDate: "09/21/1937",
        pages: 320,
        productDimensions: "5.30(w) x 8.00(h) x 0.90(d)",
        overview: "J.R.R. Tolkien's classic fantasy novel follows Bilbo Baggins on an epic adventure to reclaim treasure guarded by the dragon Smaug.",
        tableOfContent: ["Chapter 1: An Unexpected Party", "Chapter 2: Roast Mutton", "Chapter 3: A Short Rest", "Chapter 4: Over Hill and Under Hill"],
    },
];

var nonficBooks = [
    {
        bookTitle: "Atomic Habits",
        bookAuthor: "James Clear",
        bookCover: "images/Atomic Habits.jpg",
        bookRating: 4,
        bookPrice: 10,
        ISBN: 9780735211292,
        publisher: "Penguin Publishing Group",
        publicationDate: "10/16/2018",
        pages: 320,
        productDimensions: "6.20(w) x 8.90(h) x 1.20(d)",
        overview: "Thoughtful and easy to understand, James Clear’s Atomic Habits is a must for anyone trying to change their productivity. This simple guide will help create a strong foundation for building good habits and make it easy to say goodbye to bad habits for good.",
        tableOfContent: ["Introduction", "The Fundamentals", "The Four Laws of Behavior Change", "Advanced Tactics"],
    },
    {
        bookTitle: "Freakonomics: A Rogue Economist Explores the Hidden Side of Everything",
        bookAuthor: "Steven D. Levitt",
        bookCover: "images/Freakonomics A Rogue Economist Explores the Hidden Side of Everything.jpg",
        bookRating: 3.8,
        bookPrice: 10,
        ISBN: 9780060731328,
        publisher: "William Morrow",
        publicationDate: "04/12/2005",
        pages: 336,
        productDimensions: "5.31(w) x 8.00(h) x 0.76(d)",
        overview: "Freakonomics explores the hidden side of everything, using economic theory to explain real-world phenomena in surprising ways.",
        tableOfContent: ["What Do Schoolteachers and Sumo Wrestlers Have in Common?", "How Is the Ku Klux Klan Like a Group of Real-Estate Agents?", "Why Do Drug Dealers Still Live with Their Moms?", "Where Have All the Criminals Gone?"],
    },
    {
        bookTitle: "Nudge: Improving Decisions About Health, Wealth, and Happiness",
        bookAuthor: "Richard H. Thaler",
        bookCover: "images/Nudge Improving Decisions About Health, Wealth, and Happiness.jpg",
        bookRating: 3.5,
        bookPrice: 1,
        ISBN: 9780143115267,
        publisher: "Penguin Books",
        publicationDate: "02/24/2009",
        pages: 320,
        productDimensions: "5.50(w) x 8.40(h) x 0.90(d)",
        overview: "Nudge is a groundbreaking book that shows how we can make better decisions about health, wealth, and happiness.",
        tableOfContent: ["Biases and Blunders", "Resisting Temptation", "Choice Architecture", "Saving the Planet"],
    },
    {
        bookTitle: "The Drunkard's Walk: How Randomness Rules Our Lives",
        bookAuthor: "Leonard Mlodinow",
        bookCover: "images/The Drunkard's Walk How Randomness Rules Our Lives.jpg",
        bookRating: 3.9,
        bookPrice: 10,
        ISBN: 9780307275172,
        publisher: "Vintage",
        publicationDate: "05/05/2009",
        pages: 252,
        productDimensions: "5.20(w) x 8.00(h) x 0.70(d)",
        overview: "The Drunkard's Walk explores the role of randomness in our lives and how it influences our decisions and outcomes.",
        tableOfContent: ["The Laws of Randomness", "The Role of Probability", "The Illusion of Patterns", "The Power of Chance"],
    },
    {
        bookTitle: "The Let Them Theory: A Life-Changing Tool That Millions of People Can't Stop Talking About",
        bookAuthor: "Mel Robbins",
        bookCover: "images/The Let Them Theory A Life-Changing Tool That Millions of People Can't Stop Talking About.jpg",
        bookRating: 3.5,
        bookPrice: 10,
        ISBN: 9781401967490,
        publisher: "Hay House Inc.",
        publicationDate: "09/28/2021",
        pages: 240,
        productDimensions: "5.50(w) x 8.50(h) x 0.80(d)",
        overview: "Mel Robbins introduces the 'Let Them Theory,' a simple yet powerful tool for overcoming challenges and achieving personal growth.",
        tableOfContent: ["The Theory", "Applying the Theory", "Overcoming Obstacles", "Achieving Success"],
    },
    {
        bookTitle: "Abundance",
        bookAuthor: "Ezra Klein",
        bookCover: "images/Abundance.jpg",
        bookRating: 3.9,
        bookPrice: 10,
        ISBN: 9781451614213,
        publisher: "Simon & Schuster",
        publicationDate: "02/21/2012",
        pages: 432,
        productDimensions: "6.00(w) x 9.00(h) x 1.20(d)",
        overview: "Abundance explores how technological innovation and human ingenuity are solving the world's biggest challenges.",
        tableOfContent: ["The Future of Innovation", "Solving Global Problems", "The Role of Technology", "A Vision for Tomorrow"],
    },
    {
        bookTitle: "Murdle: Volume 1: 100 Elementary to Impossible Mysteries to Solve Using Logic, Skill, and the Power of Deduction",
        bookAuthor: "G. T. Karber",
        bookCover: "images/murdle vol1.jpg",
        bookRating: 4.8,
        bookPrice: 10,
        ISBN: 9781523518477,
        publisher: "Workman Publishing Company",
        publicationDate: "10/18/2022",
        pages: 288,
        productDimensions: "7.00(w) x 9.00(h) x 0.80(d)",
        overview: "Murdle is a collection of 100 mysteries designed to challenge your logic, deduction, and problem-solving skills.",
        tableOfContent: ["Elementary Mysteries", "Intermediate Mysteries", "Advanced Mysteries", "Impossible Mysteries"],
    },
    {
        bookTitle: "The Body Keeps the Score: Brain, Mind, and Body in the Healing of Trauma",
        bookAuthor: "Bessel van der Kolk M.D.",
        bookCover: "images/The Body Keeps the Score Brain, Mind, and Body in the Healing of Trauma.jpg",
        bookRating: 4.3,
        bookPrice: 10,
        ISBN: 9780143127741,
        publisher: "Penguin Books",
        publicationDate: "09/08/2015",
        pages: 464,
        productDimensions: "5.50(w) x 8.40(h) x 1.10(d)",
        overview: "The Body Keeps the Score is a groundbreaking book on trauma and its impact on the brain, mind, and body.",
        tableOfContent: ["Understanding Trauma", "The Neuroscience of Trauma", "Healing the Mind", "Healing the Body"],
    },
    {
        bookTitle: "The 7 Habits of Highly Effective People",
        bookAuthor: "Stephen R. Covey",
        bookCover: "images/7 Habits of highly effective people.jpg",
        bookRating: 4.6,
        bookPrice: 11.99,
        ISBN: 9780743269513,
        publisher: "Free Press",
        publicationDate: "11/19/2004",
        pages: 381,
        productDimensions: "6.10(w) x 9.20(h) x 1.10(d)",
        overview: "One of the most inspiring and impactful books ever written, *The 7 Habits of Highly Effective People* has captivated readers for over 30 years. Stephen R. Covey presents a holistic, principle-centered approach for solving personal and professional problems. With penetrating insights and practical anecdotes, Covey reveals a step-by-step pathway for living with integrity, fairness, and human dignity—principles that give us the security to adapt to change and the wisdom and power to take advantage of the opportunities that change creates.",
        tableOfContent: [
            "Part One: Paradigms and Principles",
            "Part Two: Private Victory",
            "Part Three: Public Victory",
            "Part Four: Renewal"
        ]
    }
];

var bioBooks = [
    {
        bookTitle: "Steve Jobs",
        bookAuthor: "Walter Isaacson",
        bookCover: "images/steve_jobs.jpg",
        bookRating: 5,
        bookPrice: 10,
        ISBN: 9781982176860,
        publisher: "Simon & Schuster",
        publicationDate: "10/05/2021",
        pages: 672,
        productDimensions: "9.10(w) x 6.00(h) x 1.70(d)",
        overview: "Based on more than forty interviews with Steve Jobs conducted over two years—as well as interviews with more than 100 family members, friends, adversaries, competitors, and colleagues—Walter Isaacson has written a riveting story of the roller-coaster life and searingly intense personality of a creative entrepreneur whose passion for perfection and ferocious drive revolutionized six industries.",
        tableOfContent: ["Characters xiii", "Introduction: How This Book Came to Be xvii", "Chapter 1 Childhood: Abandoned and Chosen 1", "Chapter 2 Odd Couple: The Two Steves 21", "Chapter 3 The Dropout: Turn On, Tune In 31", "Chapter 4 Atari and India: Zen and the Art of Game Design 42"],
    },
    {
        bookTitle: "American Prometheus: The Triumph and Tragedy of J. Robert Oppenheimer",
        bookAuthor: "Kai Bird",
        bookCover: "images/American Prometheus The Triumph and Tragedy of J. Robert Oppenheimer.jpg",
        bookRating: 4.3,
        bookPrice: 10,
        ISBN: 9780375726262,
        publisher: "Vintage",
        publicationDate: "04/11/2006",
        pages: 784,
        productDimensions: "6.10(w) x 9.20(h) x 1.50(d)",
        overview: "A biography of J. Robert Oppenheimer, the father of the atomic bomb, exploring his life, achievements, and the moral dilemmas he faced.",
        tableOfContent: ["Prologue", "Part 1: The Early Years", "Part 2: The Manhattan Project", "Part 3: The Fallout"],
    },
    {
        bookTitle: "Mao: The Unknown Story",
        bookAuthor: "Jung Chang",
        bookCover: "images/Mao The Unknown Story.jpg",
        bookRating: 5,
        bookPrice: 10,
        ISBN: 9780679746324,
        publisher: "Anchor",
        publicationDate: "06/06/2006",
        pages: 864,
        productDimensions: "6.10(w) x 9.20(h) x 1.80(d)",
        overview: "A groundbreaking biography of Mao Zedong, revealing the untold story of his life and the devastating impact of his rule on China.",
        tableOfContent: ["Introduction", "Part 1: The Rise of Mao", "Part 2: The Great Leap Forward", "Part 3: The Cultural Revolution"],
    },
    {
        bookTitle: "Einstein: His Life and Universe",
        bookAuthor: "Walter Isaacson",
        bookCover: "images/Einstein His Life and Universe.jpg",
        bookRating: 4.1,
        bookPrice: 10,
        ISBN: 9780743264747,
        publisher: "Simon & Schuster",
        publicationDate: "04/10/2007",
        pages: 704,
        productDimensions: "6.10(w) x 9.20(h) x 1.50(d)",
        overview: "A comprehensive biography of Albert Einstein, exploring his scientific achievements and personal life.",
        tableOfContent: ["Prologue", "Chapter 1: The Early Years", "Chapter 2: The Miracle Year", "Chapter 3: Relativity", "Chapter 4: The Later Years"],
    },
    {
        bookTitle: "Benjamin Franklin: An American Life",
        bookAuthor: "Walter Isaacson",
        bookCover: "images/Benjamin Franklin An American Life.jpg",
        bookRating: 4.1,
        bookPrice: 10,
        ISBN: 9780743258074,
        publisher: "Simon & Schuster",
        publicationDate: "07/01/2004",
        pages: 608,
        productDimensions: "6.10(w) x 9.20(h) x 1.40(d)",
        overview: "A biography of Benjamin Franklin, exploring his life as a scientist, inventor, diplomat, and one of America's founding fathers.",
        tableOfContent: ["Introduction", "Chapter 1: The Young Franklin", "Chapter 2: The Inventor", "Chapter 3: The Diplomat", "Chapter 4: The Founding Father"],
    },
    {
        bookTitle: "Galileo's Daughter: A Historical Memoir of Science, Faith, and Love",
        bookAuthor: "Dava Sobel",
        bookCover: "images/Galileo's Daughter A Historical Memoir of Science, Faith, and Love.jpg",
        bookRating: 3.7,
        bookPrice: 10,
        ISBN: 9780140280555,
        publisher: "Penguin Books",
        publicationDate: "09/05/2000",
        pages: 432,
        productDimensions: "5.50(w) x 8.40(h) x 1.10(d)",
        overview: "A historical memoir exploring the relationship between Galileo Galilei and his daughter, Maria Celeste, set against the backdrop of the scientific revolution.",
        tableOfContent: ["Prologue", "Chapter 1: The Early Years", "Chapter 2: The Trial", "Chapter 3: The Letters", "Chapter 4: The Legacy"],
    },
    {
        bookTitle: "John Adams",
        bookAuthor: "David McCullough",
        bookCover: "images/john adams.jpg",
        bookRating: 4.4,
        bookPrice: 10,
        ISBN: 9780743223133,
        publisher: "Simon & Schuster",
        publicationDate: "05/22/2001",
        pages: 752,
        productDimensions: "6.10(w) x 9.20(h) x 1.60(d)",
        overview: "A biography of John Adams, the second president of the United States, exploring his role in the American Revolution and the founding of the nation.",
        tableOfContent: ["Introduction", "Chapter 1: The Early Years", "Chapter 2: The Revolution", "Chapter 3: The Presidency", "Chapter 4: The Legacy"],
    },
    {
        bookTitle: "The Autobiography of Malcolm X",
        bookAuthor: "Malcolm X",
        bookCover: "images/The Autobiography of Malcolm X.jpg",
        bookRating: 4.4,
        bookPrice: 10,
        ISBN: 9780345350688,
        publisher: "Ballantine Books",
        publicationDate: "10/12/1987",
        pages: 460,
        productDimensions: "5.50(w) x 8.40(h) x 1.10(d)",
        overview: "The autobiography of Malcolm X, chronicling his journey from a troubled youth to a prominent civil rights leader.",
        tableOfContent: ["Introduction", "Chapter 1: The Early Years", "Chapter 2: The Nation of Islam", "Chapter 3: The Pilgrimage", "Chapter 4: The Legacy"],
    },
    {
        bookTitle: "Alexander Hamilton",
        bookAuthor: "Ron Chernow",
        bookCover: "images/Alexander Hamilton.jpg",
        bookRating: 4.2,
        bookPrice: 10,
        ISBN: 9780143034759,
        publisher: "Penguin Books",
        publicationDate: "04/26/2005",
        pages: 832,
        productDimensions: "6.10(w) x 9.20(h) x 1.70(d)",
        overview: "A biography of Alexander Hamilton, exploring his role as a founding father of the United States and his contributions to the nation's financial system.",
        tableOfContent: ["Introduction", "Chapter 1: The Early Years", "Chapter 2: The Revolutionary War", "Chapter 3: The Federalist Papers", "Chapter 4: The Legacy"],
    },
    {
        bookTitle: "The Da Vinci Code",
        bookAuthor: "Dan Brown",
        bookCover: "images/The Da Vinci Code.jpg",
        bookRating: 4.5,
        bookPrice: 9.99,
        ISBN: 9780307474278,
        publisher: "Anchor",
        publicationDate: "03/31/2009",
        pages: 489,
        productDimensions: "5.20(w) x 8.00(h) x 1.10(d)",
        overview: "THE #1 WORLDWIDE BESTSELLING PHENOMENON, WITH MORE THAN 85 MILLION COPIES SOLD. “Blockbuster perfection . . . a gleefully erudite suspense novel.” —The New York Times. “A pulse-quickening, brain-teasing adventure.” —People. While in Paris, Harvard symbologist Robert Langdon is awakened by a phone call in the dead of the night. The elderly curator of the Louvre has been murdered inside the museum, his body covered in baffling symbols. As Langdon and gifted French cryptologist Sophie Neveu sort through the bizarre riddles, they are stunned to discover a trail of clues hidden in the works of Leonardo da Vinci—clues visible for all to see and yet ingeniously disguised by the painter. Even more startling, the late curator was involved in the Priory of Sion, a secret society whose members included Sir Isaac Newton, Victor Hugo, and Da Vinci, and he guarded a breathtaking historical secret. Unless Langdon and Neveu can decipher the labyrinthine puzzle—while avoiding the faceless adversary who shadows their every move—the explosive, ancient truth will be lost forever.",
        tableOfContent: ["Prologue", "Chapter 1: The Louvre", "Chapter 2: The Cryptex", "Chapter 3: The Priory of Sion", "Chapter 4: The Truth Revealed"]
    }
];
var horrorBooks = [
    {
        bookTitle: "Never Flinch: A Novel",
        bookAuthor: "Stephen King",
        bookCover: "images/booksCovers/Never Flinch A Novel.jpg",
        bookRating: 5,
        bookPrice: 22.40,
        ISBN: 9781668089330,
        publisher: "Scribner",
        publicationDate: "05/27/2025",
        pages: 448,
        productDimensions: "6.12(w) x 9.25(h) x 1.50(d)",
        overview: "An elusive heiress, a love story and a mystery. Cathartic, romantic, tragic and charming, Emily Henry told her readers this book challenged her like no other. Grab an extra copy — you’ll want to share it with everyone you know.\n\nThis Barnes and Noble Exclusive edition includes a special colorway, beautiful endpapers, and an alternate case color with an exclusive foil-stamped quote.\nTwo writers compete for the chance to tell the larger-than-life story of a woman with more than a couple of plot twists up her sleeve in this dazzling and sweeping new novel from Emily Henry.",
        tableOfContent: ["#", "#", "#", "#"],
    },
    {
        bookTitle: "It",
        bookAuthor: "Stephen King",
        bookCover: "images/booksCovers/It.jpg",
        bookRating: 5,
        bookPrice: 18.99,
        ISBN: 9780450411434,
        publisher: "Viking",
        publicationDate: "09/15/1986",
        pages: 1138,
        productDimensions: "6.10(w) x 9.20(h) x 2.50(d)",
        overview: "A group of children face an ancient, shape-shifting evil that emerges every 27 years to prey on the town of Derry, Maine. Decades later, they reunite to confront their fears and destroy the monster once and for all.",
        tableOfContent: ["Part 1: The Shadow Before", "Part 2: June of 1958", "Part 3: Grownups", "Part 4: July of 1958", "Part 5: The Ritual of Chüd"],
    },
    {
        bookTitle: "The Haunting of Hill House",
        bookAuthor: "Shirley Jackson",
        bookCover: "images/booksCovers/The Haunting of Hill House.jpg",
        bookRating: 4.8,
        bookPrice: 14.99,
        ISBN: 9780143039983,
        publisher: "Penguin Classics",
        publicationDate: "10/16/1959",
        pages: 246,
        productDimensions: "5.50(w) x 8.40(h) x 0.70(d)",
        overview: "Four seekers arrive at a notoriously unfriendly mansion called Hill House. At first, their stay seems destined to be merely a spooky encounter, but Hill House is gathering its powers—and soon it will choose one of them to make its own.",
        tableOfContent: ["Chapter 1", "Chapter 2", "Chapter 3", "Chapter 4", "Chapter 5"],
    },
    {
        bookTitle: "Dracula",
        bookAuthor: "Bram Stoker",
        bookCover: "images/booksCovers/Dracula.jpg",
        bookRating: 4.7,
        bookPrice: 12.50,
        ISBN: 9780141439846,
        publisher: "Penguin Classics",
        publicationDate: "05/26/1897",
        pages: 488,
        productDimensions: "5.10(w) x 7.80(h) x 1.10(d)",
        overview: "The classic Gothic horror novel that introduced Count Dracula to the world. A tale of suspense, terror, and the eternal struggle between good and evil.",
        tableOfContent: ["Jonathan Harker's Journal", "Mina Murray's Journal", "Dr. Seward's Diary", "The Hunt for Dracula"],
    },
    {
        bookTitle: "The Shining",
        bookAuthor: "Stephen King",
        bookCover: "images/booksCovers/The Shining.jpg",
        bookRating: 5,
        bookPrice: 16.99,
        ISBN: 9780307743657,
        publisher: "Anchor",
        publicationDate: "01/28/1977",
        pages: 659,
        productDimensions: "5.50(w) x 8.20(h) x 1.50(d)",
        overview: "Jack Torrance becomes the winter caretaker at the isolated Overlook Hotel in Colorado, hoping to cure his writer's block. But as the harsh winter sets in, the hotel's dark secrets begin to surface, and Jack's sanity unravels.",
        tableOfContent: ["Part 1: Prefatory Matters", "Part 2: Closing Day", "Part 3: The Wasps' Nest", "Part 4: Snowbound", "Part 5: Matters of Life and Death"],
    },
    {
        bookTitle: "Pet Sematary",
        bookAuthor: "Stephen King",
        bookCover: "images/booksCovers/Pet Sematary.jpg",
        bookRating: 4.9,
        bookPrice: 15.99,
        ISBN: 9780743412285,
        publisher: "Pocket Books",
        publicationDate: "11/14/1983",
        pages: 416,
        productDimensions: "5.50(w) x 8.25(h) x 1.00(d)",
        overview: "When Louis Creed moves his family to a rural town, he discovers a mysterious burial ground that brings the dead back to life—with horrifying consequences.",
        tableOfContent: ["Part 1: The Pet Sematary", "Part 2: The Micmac Burial Ground", "Part 3: The Return"],
    },
    {
        bookTitle: "Frankenstein",
        bookAuthor: "Mary Shelley",
        bookCover: "images/booksCovers/Frankenstein.jpg",
        bookRating: 4.8,
        bookPrice: 10.99,
        ISBN: 9780486282114,
        publisher: "Dover Publications",
        publicationDate: "01/01/1818",
        pages: 166,
        productDimensions: "5.00(w) x 8.00(h) x 0.50(d)",
        overview: "A classic tale of horror and science fiction, Frankenstein tells the story of Victor Frankenstein and the monstrous creation that haunts him.",
        tableOfContent: ["Letter 1", "Chapter 1", "Chapter 2", "Chapter 3", "Chapter 4"],
    },
    {
        bookTitle: "The Exorcist",
        bookAuthor: "William Peter Blatty",
        bookCover: "images/booksCovers/The Exorcist.jpg",
        bookRating: 4.7,
        bookPrice: 14.99,
        ISBN: 9780061007224,
        publisher: "HarperTorch",
        publicationDate: "10/01/1971",
        pages: 400,
        productDimensions: "5.30(w) x 8.00(h) x 1.00(d)",
        overview: "A chilling story of demonic possession and the battle between good and evil, The Exorcist is a masterpiece of horror fiction.",
        tableOfContent: ["Part 1: The Beginning", "Part 2: The Possession", "Part 3: The Exorcism"],
    },
    {
        bookTitle: "Bird Box",
        bookAuthor: "Josh Malerman",
        bookCover: "images/booksCovers/Bird Box.jpg",
        bookRating: 4.5,
        bookPrice: 13.99,
        ISBN: 9780062259660,
        publisher: "Ecco",
        publicationDate: "05/13/2014",
        pages: 272,
        productDimensions: "5.50(w) x 8.25(h) x 0.80(d)",
        overview: "In a world where unseen creatures drive people to madness and death, a mother and her children must navigate a treacherous journey blindfolded to survive.",
        tableOfContent: ["Chapter 1", "Chapter 2", "Chapter 3", "Chapter 4", "Chapter 5"],
    },
];
// Mystery & Thriller Books
var mysteryThrillerBooks = [
    {
        bookTitle: "The Silent Patient",
        bookAuthor: "Alex Michaelides",
        bookCover: "images/booksCovers/The Silent Patient.jpg",
        bookRating: 4.9,
        bookPrice: 17.99,
        ISBN: 9781250301697,
        publisher: "Celadon Books",
        publicationDate: "02/05/2019",
        pages: 336,
        productDimensions: "6.10(w) x 9.30(h) x 1.30(d)",
        overview: "Alicia Berenson's life is seemingly perfect. A famous painter married to an in-demand fashion photographer, she lives in a grand house overlooking a park in London. One evening, her husband Gabriel returns home late, and Alicia shoots him five times in the face and then never speaks another word.",
        tableOfContent: ["Part 1: The Silent Patient", "Part 2: The Diary", "Part 3: The Revelation"],
    },
    {
        bookTitle: "Gone Girl",
        bookAuthor: "Gillian Flynn",
        bookCover: "images/booksCovers/Gone Girl.jpg",
        bookRating: 4.8,
        bookPrice: 15.99,
        ISBN: 9780307588371,
        publisher: "Crown",
        publicationDate: "06/05/2012",
        pages: 432,
        productDimensions: "5.50(w) x 8.25(h) x 1.10(d)",
        overview: "On their fifth wedding anniversary, Nick Dunne reports that his wife Amy is missing. Under pressure from the police and a growing media frenzy, Nick's portrait of a blissful union begins to crumble. Soon his lies, deceits and strange behavior have everyone asking the same dark question: Did Nick Dunne kill his wife?",
        tableOfContent: ["Part 1: Boy Loses Girl", "Part 2: Boy Meets Girl", "Part 3: Boy Gets Girl Back (Or Vice Versa)"],
    },
    {
        bookTitle: "The Girl with the Dragon Tattoo",
        bookAuthor: "Stieg Larsson",
        bookCover: "images/the girl with the dragon tattoo.jpg",
        bookRating: 4.7,
        bookPrice: 16.95,
        ISBN: 9780307454546,
        publisher: "Vintage Crime/Black Lizard",
        publicationDate: "06/23/2009",
        pages: 672,
        productDimensions: "5.17(w) x 7.98(h) x 1.43(d)",
        overview: "Mikael Blomkvist, a disgraced journalist, and Lisbeth Salander, a tattooed and pierced hacker, team up to investigate the decades-old disappearance of Harriet Vanger, a member of one of Sweden's wealthiest families.",
        tableOfContent: ["Prologue", "Part 1: A Family Chronicle", "Part 2: The Equation of Love", "Part 3: Mergers", "Part 4: Hostile Takeover"],
    },
    {
        bookTitle: "The Da Vinci Code",
        bookAuthor: "Dan Brown",
        bookCover: "images/The Da Vinci Code.jpg",
        bookRating: 4.6,
        bookPrice: 14.99,
        ISBN: 9780307474278,
        publisher: "Anchor",
        publicationDate: "03/28/2006",
        pages: 496,
        productDimensions: "5.20(w) x 8.00(h) x 1.10(d)",
        overview: "Harvard symbologist Robert Langdon and cryptologist Sophie Neveu uncover a series of clues in the works of Leonardo da Vinci after a murder in the Louvre Museum, leading them on a journey through France and England to discover a secret protected by a clandestine society since the time of Christ.",
        tableOfContent: ["Prologue", "Part 1: Paris", "Part 2: London", "Part 3: Revelation", "Epilogue"],
    },
    {
        bookTitle: "The Wife Between Us",
        bookAuthor: "Greer Hendricks and Sarah Pekkanen",
        bookCover: "images/booksCovers/The Wife Between Us.jpg",
        bookRating: 4.5,
        bookPrice: 16.99,
        ISBN: 9781250130921,
        publisher: "St. Martin's Press",
        publicationDate: "01/09/2018",
        pages: 352,
        productDimensions: "6.10(w) x 9.30(h) x 1.30(d)",
        overview: "A novel of suspense that explores the complexities of marriage and the dangerous truths we ignore in the name of love. When you read this book, you will make many assumptions. You will assume you are reading about a jealous ex-wife. But nothing is what it seems.",
        tableOfContent: ["Part 1: The Ex-Wife", "Part 2: The Wife", "Part 3: The Truth"],
    },
    {
        bookTitle: "The Woman in the Window",
        bookAuthor: "A.J. Finn",
        bookCover: "images/booksCovers/The Woman in the Window.jpg",
        bookRating: 4.4,
        bookPrice: 16.99,
        ISBN: 9780062678416,
        publisher: "William Morrow",
        publicationDate: "01/02/2018",
        pages: 464,
        productDimensions: "6.00(w) x 9.00(h) x 1.17(d)",
        overview: "Anna Fox lives alone, a recluse in her New York City home, drinking too much wine, watching old movies, and spying on her neighbors. But when she sees something she shouldn't, Anna's world begins to crumble—and its shocking secrets are laid bare.",
        tableOfContent: ["Part 1: The Shadow", "Part 2: The Watcher", "Part 3: The Prisoner", "Part 4: The Flight"],
    },
    {
        bookTitle: "The Guest List",
        bookAuthor: "Lucy Foley",
        bookCover: "images/booksCovers/The Guest List.jpg",
        bookRating: 4.5,
        bookPrice: 16.99,
        ISBN: 9780062868930,
        publisher: "William Morrow",
        publicationDate: "06/02/2020",
        pages: 320,
        productDimensions: "6.00(w) x 9.00(h) x 1.05(d)",
        overview: "On an island off the coast of Ireland, guests gather to celebrate the wedding of a rising television star and a magazine publisher. But as the festivities begin, resentments and petty jealousies surface, and as the storm outside intensifies, someone turns up dead.",
        tableOfContent: ["The Morning of the Wedding", "The Night Before", "The Day Before", "Two Days Before", "The Wedding Night"],
    },
    {
        bookTitle: "Before I Go to Sleep",
        bookAuthor: "S.J. Watson",
        bookCover: "images/booksCovers/Before I Go to Sleep.jpg",
        bookRating: 4.3,
        bookPrice: 15.99,
        ISBN: 9780062060556,
        publisher: "Harper",
        publicationDate: "06/14/2011",
        pages: 368,
        productDimensions: "5.31(w) x 8.00(h) x 0.83(d)",
        overview: "Every day Christine wakes up not knowing where she is or who she is. Her memories disappear every time she falls asleep. Her husband, Ben, is a stranger to her, and he's obligated to explain their life together on a daily basis. But one day, Christine finds a journal labeled with her name and a terrifying message: 'Don't trust Ben.'",
        tableOfContent: ["Part 1: Today", "Part 2: The Journal", "Part 3: The Truth"],
    },
    {
        bookTitle: "The Whisper Man",
        bookAuthor: "Alex North",
        bookCover: "images/booksCovers/The Whisper Man.jpg",
        bookRating: 4.6,
        bookPrice: 16.99,
        ISBN: 9781250317995,
        publisher: "Celadon Books",
        publicationDate: "08/20/2019",
        pages: 368,
        productDimensions: "6.10(w) x 9.30(h) x 1.20(d)",
        overview: "After the sudden death of his wife, Tom Kennedy believes a fresh start will help him and his young son Jake heal. But the town they move to has a dark past. Twenty years ago, a serial killer abducted and murdered five residents. Now, children are disappearing again.",
        tableOfContent: ["Part 1: The Whisper Man", "Part 2: The Copycat", "Part 3: The Truth"],
    },
];

// History Books
var historyBooks = [
    {
        bookTitle: "The Silk Roads: A New History of the World",
        bookAuthor: "Peter Frankopan",
        bookCover: "images/booksCovers/The Silk Roads A New History of the World.jpg",
        bookRating: 4.6,
        bookPrice: 22.00,
        ISBN: 9781101946329,
        publisher: "Knopf",
        publicationDate: "02/16/2016",
        pages: 656,
        productDimensions: "6.50(w) x 9.50(h) x 1.80(d)",
        overview: "Far more than a history of the Silk Roads, this book is truly a revelatory new history of the world, promising to destabilize notions of where we come from and where we are headed next. From the Middle East and its political instability to China and its economic rise, the vast region stretching eastward from the Balkans across the steppe and South Asia has been thrust into the global spotlight in recent years.",
        tableOfContent: ["Part 1: The Creation of the Silk Road", "Part 2: The Road of Faiths", "Part 3: The Road to a Christian East", "Part 4: The Road to Revolution", "Part 5: The Road to Concord", "Part 6: The Road to Superpower Rivalry"],
    },
    {
        bookTitle: "SPQR: A History of Ancient Rome",
        bookAuthor: "Mary Beard",
        bookCover: "images/booksCovers/SPQR A History of Ancient Rome.jpg",
        bookRating: 4.6,
        bookPrice: 17.95,
        ISBN: 9781631492228,
        publisher: "Liveright",
        publicationDate: "09/06/2016",
        pages: 608,
        productDimensions: "5.50(w) x 8.30(h) x 1.60(d)",
        overview: "Ancient Rome matters. Its history of empire, conquest, cruelty, and excess is something against which we still judge ourselves. Its myths and stories - from Romulus and Remus to the Rape of Lucretia - still strike a chord with us. And its debates about citizenship, responsibility, and the state still influence our own debates on civil liberty today.",
        tableOfContent: ["Chapter 1: Cicero's Finest Hour", "Chapter 2: In the Beginning", "Chapter 3: The Kings of Rome", "Chapter 4: Rome's Great Leap Forward", "Chapter 5: A Wider World", "Chapter 6: New Politics"],
    },
    {
        bookTitle: "Guns, Germs, and Steel",
        bookAuthor: "Jared Diamond",
        bookCover: "images/booksCovers/Guns Germs and Steel.jpg",
        bookRating: 4.5,
        bookPrice: 18.95,
        ISBN: 9780393354324,
        publisher: "W. W. Norton & Company",
        publicationDate: "04/01/1999",
        pages: 528,
        productDimensions: "5.50(w) x 8.30(h) x 1.30(d)",
        overview: "In this Pulitzer Prize-winning book, Jared Diamond argues that geographical and environmental factors shaped the modern world. Societies that had a head start in food production advanced beyond the hunter-gatherer stage, and then developed writing, technology, and organized political structures.",
        tableOfContent: ["Part 1: From Eden to Cajamarca", "Part 2: The Rise and Spread of Food Production", "Part 3: From Food to Guns, Germs, and Steel", "Part 4: Around the World in Five Chapters"],
    },
    {
        bookTitle: "The Origins of Totalitarianism",
        bookAuthor: "Hannah Arendt",
        bookCover: "images/booksCovers/The Origins of Totalitarianism.jpg",
        bookRating: 4.7,
        bookPrice: 19.95,
        ISBN: 9780156701532,
        publisher: "Harvest Books",
        publicationDate: "03/21/1973",
        pages: 576,
        productDimensions: "5.31(w) x 8.00(h) x 1.50(d)",
        overview: "Hannah Arendt's definitive work on totalitarianism traces the origins of both anti-Semitism and imperialism, and analyses the institutions and operations of totalitarian movements and regimes. It remains one of the most influential works of political philosophy of the 20th century.",
        tableOfContent: ["Part 1: Antisemitism", "Part 2: Imperialism", "Part 3: Totalitarianism"],
    },
    {
        bookTitle: "A People's History of the United States",
        bookAuthor: "Howard Zinn",
        bookCover: "images/booksCovers/A People's History of the United States.jpg",
        bookRating: 4.7,
        bookPrice: 21.99,
        ISBN: 9780062397348,
        publisher: "Harper Perennial Modern Classics",
        publicationDate: "11/17/2015",
        pages: 768,
        productDimensions: "5.31(w) x 8.00(h) x 1.73(d)",
        overview: "Known for its lively, clear prose as well as its scholarly research, A People's History of the United States is the only volume to tell America's story from the point of view of—and in the words of—America's women, factory workers, African-Americans, Native Americans, the working poor, and immigrant laborers.",
        tableOfContent: ["Chapter 1: Columbus, the Indians, and Human Progress", "Chapter 2: Drawing the Color Line", "Chapter 3: Persons of Mean and Vile Condition", "Chapter 4: Tyranny Is Tyranny", "Chapter 5: A Kind of Revolution"],
    },
    {
        bookTitle: "The Crusades: The Authoritative History of the War for the Holy Land",
        bookAuthor: "Thomas Asbridge",
        bookCover: "images/booksCovers/The Crusades.jpg",
        bookRating: 4.6,
        bookPrice: 19.99,
        ISBN: 9780060787295,
        publisher: "Ecco",
        publicationDate: "03/08/2011",
        pages: 784,
        productDimensions: "5.31(w) x 8.00(h) x 1.77(d)",
        overview: "The Crusades is an authoritative, accessible single-volume history of the brutal struggle for the Holy Land in the Middle Ages. Thomas Asbridge tells the story of the Crusades with unprecedented authority, using first-hand accounts from both sides to create a vivid historical narrative.",
        tableOfContent: ["Part 1: Origins and Early Crusades", "Part 2: The Crusader States", "Part 3: The Later Crusades", "Part 4: Legacy and Memory"],
    },
    {
        bookTitle: "The Rise and Fall of the Third Reich",
        bookAuthor: "William L. Shirer",
        bookCover: "images/booksCovers/The Rise and Fall of the Third Reich.jpg",
        bookRating: 4.7,
        bookPrice: 29.99,
        ISBN: 9781451651683,
        publisher: "Simon & Schuster",
        publicationDate: "10/11/2011",
        pages: 1280,
        productDimensions: "6.13(w) x 9.25(h) x 2.50(d)",
        overview: "Since its publication in 1960, William L. Shirer's monumental study of Hitler's German empire has been widely acclaimed as the definitive record of the 20th century's blackest hours. The Rise and Fall of the Third Reich offers an unparalleled and thrillingly told examination of how Adolf Hitler nearly succeeded in conquering the world.",
        tableOfContent: ["Book 1: The Rise of Adolf Hitler", "Book 2: Triumph and Consolidation", "Book 3: The Road to War", "Book 4: War: Early Victories and the Turning Point", "Book 5: Beginning of the End", "Book 6: The Fall of the Third Reich"],
    },
    {
        bookTitle: "1491: New Revelations of the Americas Before Columbus",
        bookAuthor: "Charles C. Mann",
        bookCover: "images/booksCovers/1941.jpg",
        bookRating: 4.6,
        bookPrice: 18.00,
        ISBN: 9781400032051,
        publisher: "Vintage",
        publicationDate: "10/10/2006",
        pages: 541,
        productDimensions: "5.20(w) x 8.00(h) x 1.20(d)",
        overview: "In this groundbreaking work of science, history, and archaeology, Charles C. Mann radically alters our understanding of the Americas before the arrival of Columbus in 1492. Contrary to what so many Americans learn in school, the pre-Columbian Indians were not sparsely settled in a pristine wilderness; rather, there were huge numbers of them actively molding and influencing the land around them.",
        tableOfContent: ["Part 1: Numbers from Nowhere?", "Part 2: Very Old Bones", "Part 3: Landscape with Figures"],
    },
];

var mangaBooks = [
    {
        bookTitle: "Attack on Titan Vol. 1",
        bookAuthor: "Hajime Isayama",
        bookCover: "images/booksCovers/Aot.jpg",
        bookRating: 4.9,
        bookPrice: 10.99,
        ISBN: 9781612620244,
        publisher: "Kodansha Comics",
        publicationDate: "06/19/2012",
        pages: 208,
        productDimensions: "5.00(w) x 7.50(h) x 0.70(d)",
        overview: "In a world where humanity lives inside cities surrounded by enormous walls due to the Titans, gigantic humanoid creatures who devour humans seemingly without reason, a young boy named Eren Yeager dreams of exploring the world beyond the walls after the appearance of a colossal Titan brings destruction to his hometown.",
        tableOfContent: ["Chapter 1: To You, 2000 Years From Now", "Chapter 2: That Day", "Chapter 3: Night of the Disbanding Ceremony", "Chapter 4: First Battle"],
    },
    {
        bookTitle: "Death Note Vol. 1",
        bookAuthor: "Tsugumi Ohba",
        bookCover: "images/booksCovers/Death Note Vol. 1.jpg",
        bookRating: 4.9,
        bookPrice: 9.99,
        ISBN: 9781421501680,
        publisher: "VIZ Media",
        publicationDate: "10/10/2005",
        pages: 200,
        productDimensions: "5.00(w) x 7.50(h) x 0.70(d)",
        overview: "Light Yagami is a brilliant high school student who discovers a mysterious notebook called the Death Note, which has the power to kill anyone whose name is written in it. Light decides to use the notebook to rid the world of criminals, but he soon finds himself pursued by a brilliant detective known only as L.",
        tableOfContent: ["Chapter 1: Boredom", "Chapter 2: Confluence", "Chapter 3: Family", "Chapter 4: Current", "Chapter 5: Eyeball", "Chapter 6: Manipulation", "Chapter 7: Overcast"],
    },
    {
        bookTitle: "One Piece Vol. 1",
        bookAuthor: "Eiichiro Oda",
        bookCover: "images/booksCovers/One Piece Vol. 1.jpg",
        bookRating: 4.8,
        bookPrice: 9.99,
        ISBN: 9781569319017,
        publisher: "VIZ Media",
        publicationDate: "06/01/2003",
        pages: 216,
        productDimensions: "5.00(w) x 7.50(h) x 0.70(d)",
        overview: "As a child, Monkey D. Luffy was inspired to become a pirate by his idol, the pirate Red-Haired Shanks. Taking a bite of the Gum-Gum Fruit, Luffy accidentally gained the power to stretch like rubber at the cost of never being able to swim again. Years later, still vowing to become the King of the Pirates, Luffy sets out on his adventure to find the legendary One Piece.",
        tableOfContent: ["Chapter 1: Romance Dawn", "Chapter 2: They Call Him 'Straw Hat Luffy'", "Chapter 3: Enter Zoro", "Chapter 4: Marine Captain Axe-Hand Morgan", "Chapter 5: Pirate King and Master Swordsman", "Chapter 6: The First Crew Member", "Chapter 7: Friends", "Chapter 8: Nami"],
    },
    {
        bookTitle: "My Hero Academia Vol. 1",
        bookAuthor: "Kohei Horikoshi",
        bookCover: "images/booksCovers/My Hero Academia Vol. 1.jpg",
        bookRating: 4.8,
        bookPrice: 9.99,
        ISBN: 9781421582696,
        publisher: "VIZ Media",
        publicationDate: "08/04/2015",
        pages: 192,
        productDimensions: "5.00(w) x 7.50(h) x 0.70(d)",
        overview: "In a world where most people have superpowers, Izuku Midoriya has always dreamed of becoming a hero, but he was born without any powers. When he meets the world's greatest hero, All Might, his chance to join the prestigious hero academy UA High becomes possible.",
        tableOfContent: ["Chapter 1: Izuku Midoriya: Origin", "Chapter 2: That Which Is Required", "Chapter 3: Entrance Exam", "Chapter 4: Start Line", "Chapter 5: What I Can Do For Now", "Chapter 6: Rage, You Damn Nerd", "Chapter 7: Deku vs. Kacchan"],
    },
    {
        bookTitle: "Naruto Vol. 1",
        bookAuthor: "Masashi Kishimoto",
        bookCover: "images/booksCovers/Naruto Vol. 1.jpg",
        bookRating: 4.8,
        bookPrice: 9.99,
        ISBN: 9781569319000,
        publisher: "VIZ Media",
        publicationDate: "08/06/2003",
        pages: 192,
        productDimensions: "5.00(w) x 7.50(h) x 0.70(d)",
        overview: "Naruto Uzumaki is a young ninja who seeks recognition from his peers and dreams of becoming the Hokage, the leader of his village. The story follows his adventures as he searches for recognition and fulfills his dream.",
        tableOfContent: ["Chapter 1: Uzumaki Naruto", "Chapter 2: Konohamaru!", "Chapter 3: Sasuke Uchiha", "Chapter 4: Kakashi Hatake", "Chapter 5: Carelessness Is Your Worst Enemy", "Chapter 6: Not Sasuke", "Chapter 7: The Conclusion of the Test"],
    },
    {
        bookTitle: "Demon Slayer: Kimetsu no Yaiba Vol. 1",
        bookAuthor: "Koyoharu Gotouge",
        bookCover: "images/booksCovers/Demon Slayer Vol 1.jpg",
        bookRating: 4.9,
        bookPrice: 9.99,
        ISBN: 9781974700523,
        publisher: "VIZ Media",
        publicationDate: "07/03/2018",
        pages: 192,
        productDimensions: "5.00(w) x 7.50(h) x 0.70(d)",
        overview: "Tanjiro Kamado's peaceful life is shattered when his family is slaughtered by a demon. The only survivor, his sister Nezuko, has been transformed into a demon herself. Tanjiro resolves to become a demon slayer to find a cure for his sister and to avenge his family.",
        tableOfContent: ["Chapter 1: Cruelty", "Chapter 2: The Stranger", "Chapter 3: Return by Dawn", "Chapter 4: Final Selection", "Chapter 5: My Own Steel", "Chapter 6: Huff and Puff", "Chapter 7: Muzan Kibutsuji"],
    },
    {
        bookTitle: "Fullmetal Alchemist Vol. 1",
        bookAuthor: "Hiromu Arakawa",
        bookCover: "images/booksCovers/Fullmetal Alchemist Vol 1.jpg",
        bookRating: 4.9,
        bookPrice: 9.99,
        ISBN: 9781591169208,
        publisher: "VIZ Media",
        publicationDate: "05/03/2005",
        pages: 192,
        productDimensions: "5.00(w) x 7.50(h) x 0.70(d)",
        overview: "Brothers Edward and Alphonse Elric are raised by their mother Trisha Elric in the remote village of Resembool. Their father abandoned them when they were still young, and when Trisha dies of the plague, the brothers attempt to resurrect their mother with alchemy, a science that allows the user to transform matter, but at a price.",
        tableOfContent: ["Chapter 1: The Two Alchemists", "Chapter 2: The Price of Life", "Chapter 3: The Mining Town", "Chapter 4: Battle on the Train"],
    },
    {
        bookTitle: "Tokyo Ghoul Vol. 1",
        bookAuthor: "Sui Ishida",
        bookCover: "images/booksCovers/Tokyo Ghoul Vol 1.jpg",
        bookRating: 4.8,
        bookPrice: 12.99,
        ISBN: 9781421580364,
        publisher: "VIZ Media",
        publicationDate: "06/16/2015",
        pages: 224,
        productDimensions: "5.75(w) x 8.25(h) x 0.70(d)",
        overview: "Ken Kaneki is an ordinary college student until a violent encounter turns him into the first half-human, half-ghoul hybrid. Trapped between two worlds, he must survive the violent conflicts of warring ghoul factions while learning to control his new powers.",
        tableOfContent: ["Chapter 1: Tragedy", "Chapter 2: Strange Dining", "Chapter 3: Before the Incident", "Chapter 4: Coffee", "Chapter 5: Disguise", "Chapter 6: Proof", "Chapter 7: Dove", "Chapter 8: Kagune", "Chapter 9: Binge Eater"],
    },
    {
        bookTitle: "Dragon Ball Vol. 1",
        bookAuthor: "Akira Toriyama",
        bookCover: "images/booksCovers/Dragon Ball Vol 1.jpg",
        bookRating: 4.8,
        bookPrice: 9.99,
        ISBN: 9781569319208,
        publisher: "VIZ Media",
        publicationDate: "05/03/2000",
        pages: 192,
        productDimensions: "5.00(w) x 7.50(h) x 0.70(d)",
        overview: "Goku is a strange, bushy-tailed boy who spends his days hunting and eating—until he meets Bulma, a bossy beauty with boys on the brain. Together, they set off to find the seven magic Dragon Balls that can make any wish come true.",
        tableOfContent: ["Chapter 1: Bulma and Son Goku", "Chapter 2: No Balls!", "Chapter 3: Sea Monkeys", "Chapter 4: They Call Him the Turtle Hermit", "Chapter 5: Oo! Oo! Oolong!", "Chapter 6: So Long, Oolong!", "Chapter 7: Yamcha and Pu'ar"],
    },
];

var selfHelpBooks = [
    {
        bookTitle: "Atomic Habits",
        bookAuthor: "James Clear",
        bookCover: "images/Atomic Habits.jpg",
        bookRating: 4.8,
        bookPrice: 27.00,
        ISBN: 9780735211292,
        publisher: "Avery",
        publicationDate: "10/16/2018",
        pages: 320,
        productDimensions: "6.20(w) x 9.30(h) x 1.10(d)",
        overview: "No matter your goals, Atomic Habits offers a proven framework for improving--every day. James Clear, one of the world's leading experts on habit formation, reveals practical strategies that will teach you exactly how to form good habits, break bad ones, and master the tiny behaviors that lead to remarkable results.",
        tableOfContent: ["Part 1: The Fundamentals", "Part 2: Make It Obvious", "Part 3: Make It Attractive", "Part 4: Make It Easy", "Part 5: Make It Satisfying", "Part 6: Advanced Tactics"],
    },
    {
        bookTitle: "The 7 Habits of Highly Effective People",
        bookAuthor: "Stephen R. Covey",
        bookCover: "images/7 Habits of highly effective people.jpg",
        bookRating: 4.7,
        bookPrice: 18.99,
        ISBN: 9781982137274,
        publisher: "Simon & Schuster",
        publicationDate: "05/19/2020",
        pages: 464,
        productDimensions: "5.50(w) x 8.40(h) x 1.30(d)",
        overview: "One of the most inspiring and impactful books ever written, The 7 Habits of Highly Effective People has captivated readers for 30 years. It has transformed the lives of presidents and CEOs, educators and parents—millions of people of all ages and occupations.",
        tableOfContent: ["Part 1: Paradigms and Principles", "Part 2: Private Victory", "Part 3: Public Victory", "Part 4: Renewal"],
    },
    {
        bookTitle: "Man's Search for Meaning",
        bookAuthor: "Viktor E. Frankl",
        bookCover: "images/booksCovers/Mans Search for Meaning.jpg",
        bookRating: 4.7,
        bookPrice: 15.00,
        ISBN: 9780807014295,
        publisher: "Beacon Press",
        publicationDate: "06/01/2006",
        pages: 184,
        productDimensions: "5.50(w) x 8.40(h) x 0.60(d)",
        overview: "Psychiatrist Viktor Frankl's memoir has riveted generations of readers with its descriptions of life in Nazi death camps and its lessons for spiritual survival. Between 1942 and 1945 Frankl labored in four different camps, including Auschwitz, while his parents, brother, and pregnant wife perished. Based on his own experience and the experiences of others he treated later in his practice, Frankl argues that we cannot avoid suffering but we can choose how to cope with it, find meaning in it, and move forward with renewed purpose.",
        tableOfContent: ["Part 1: Experiences in a Concentration Camp", "Part 2: Logotherapy in a Nutshell", "Part 3: The Case for a Tragic Optimism"],
    },
    {
        bookTitle: "How to Win Friends and Influence People",
        bookAuthor: "Dale Carnegie",
        bookCover: "images/booksCovers/How to Win Friends and Influence People.jpg",
        bookRating: 4.7,
        bookPrice: 16.99,
        ISBN: 9780671027032,
        publisher: "Pocket Books",
        publicationDate: "10/01/1998",
        pages: 288,
        productDimensions: "5.30(w) x 8.20(h) x 0.90(d)",
        overview: "This grandfather of all people-skills books was first published in 1937. It was an overnight hit, eventually selling 15 million copies. How to Win Friends and Influence People is just as useful today as it was when it was first published, because Dale Carnegie had an understanding of human nature that will never be outdated.",
        tableOfContent: ["Part 1: Fundamental Techniques in Handling People", "Part 2: Six Ways to Make People Like You", "Part 3: How to Win People to Your Way of Thinking", "Part 4: Be a Leader: How to Change People Without Giving Offense or Arousing Resentment"],
    },
    {
        bookTitle: "The Four Agreements",
        bookAuthor: "Don Miguel Ruiz",
        bookCover: "images/booksCovers/The Four Agreements.jpg",
        bookRating: 4.7,
        bookPrice: 12.95,
        ISBN: 9781878424310,
        publisher: "Amber-Allen Publishing",
        publicationDate: "11/07/1997",
        pages: 160,
        productDimensions: "5.00(w) x 7.25(h) x 0.50(d)",
        overview: "In The Four Agreements, bestselling author don Miguel Ruiz reveals the source of self-limiting beliefs that rob us of joy and create needless suffering. Based on ancient Toltec wisdom, The Four Agreements offer a powerful code of conduct that can rapidly transform our lives to a new experience of freedom, true happiness, and love.",
        tableOfContent: ["Introduction", "Chapter 1: Domestication and the Dream of the Planet", "Chapter 2: The First Agreement", "Chapter 3: The Second Agreement", "Chapter 4: The Third Agreement", "Chapter 5: The Fourth Agreement", "Chapter 6: The Toltec Path to Freedom"],
    },
    {
        bookTitle: "You Are a Badass",
        bookAuthor: "Jen Sincero",
        bookCover: "images/booksCovers/You Are a Badass.jpg",
        bookRating: 4.7,
        bookPrice: 17.00,
        ISBN: 9780762447695,
        publisher: "Running Press",
        publicationDate: "04/23/2013",
        pages: 256,
        productDimensions: "5.20(w) x 8.20(h) x 0.80(d)",
        overview: "In this refreshingly entertaining how-to guide, bestselling author and world-traveling success coach Jen Sincero serves up 27 bitesized chapters full of hilariously inspiring stories, sage advice, easy exercises, and the occasional swear word, helping you to identify and change the self-sabotaging beliefs and behaviors that stop you from getting what you want.",
        tableOfContent: ["Part 1: How You Got This Way", "Part 2: How to Embrace Your Inner Badass", "Part 3: How to Tap into the Motherlode", "Part 4: How to Get Over Your B.S. Already", "Part 5: How to Kick Some Ass"],
    },
    {
        bookTitle: "Daring Greatly",
        bookAuthor: "Brené Brown",
        bookCover: "images/booksCovers/Daring Greatly.jpg",
        bookRating: 4.8,
        bookPrice: 17.00,
        ISBN: 9781592408412,
        publisher: "Avery",
        publicationDate: "04/07/2015",
        pages: 320,
        productDimensions: "5.20(w) x 8.00(h) x 0.90(d)",
        overview: "Every day we experience the uncertainty, risks, and emotional exposure that define what it means to be vulnerable or to dare greatly. Based on twelve years of pioneering research, Brené Brown dispels the cultural myth that vulnerability is weakness and argues that it is, in truth, our most accurate measure of courage.",
        tableOfContent: ["Chapter 1: Scarcity and Our Culture of 'Never Enough'", "Chapter 2: Debunking the Vulnerability Myths", "Chapter 3: Understanding and Combating Shame", "Chapter 4: The Vulnerability Armory", "Chapter 5: Mind the Gap", "Chapter 6: Disruptive Engagement"],
    },
    {
        bookTitle: "The Power of Now",
        bookAuthor: "Eckhart Tolle",
        bookCover: "images/booksCovers/The Power of Now.jpg",
        bookRating: 4.7,
        bookPrice: 17.00,
        ISBN: 9781577314806,
        publisher: "New World Library",
        publicationDate: "08/19/2004",
        pages: 236,
        productDimensions: "5.50(w) x 8.50(h) x 0.70(d)",
        overview: "To make the journey into the Now we will need to leave our analytical mind and its false created self, the ego, behind. From the very first page of this extraordinary book, we move rapidly into a significantly higher altitude where we breathe a lighter air. We become connected to the indestructible essence of our Being.",
        tableOfContent: ["Introduction", "Chapter 1: You Are Not Your Mind", "Chapter 2: Consciousness: The Way Out of Pain", "Chapter 3: Moving Deeply into the Now", "Chapter 4: Mind Strategies for Avoiding the Now", "Chapter 5: The State of Presence"],
    },
];

var scifiBooks = [
    {
        bookTitle: "Dune",
        bookAuthor: "Frank Herbert",
        bookCover: "images/dune.jpg",
        bookRating: 4.9,
        bookPrice: 18.00,
        ISBN: 9780441172719,
        publisher: "Ace",
        publicationDate: "08/01/1965",
        pages: 896,
        productDimensions: "4.20(w) x 7.50(h) x 1.50(d)",
        overview: "Set on the desert planet Arrakis, Dune is the story of the boy Paul Atreides, heir to a noble family tasked with ruling an inhospitable world where the only thing of value is the 'spice' melange, a drug capable of extending life and enhancing consciousness. When his family is betrayed, the destruction of Paul's family sets him on a journey toward a destiny greater than anything he could ever have imagined.",
        tableOfContent: ["Book 1: Dune", "Book 2: Muad'Dib", "Book 3: The Prophet"],
    },
    {
        bookTitle: "1984",
        bookAuthor: "George Orwell",
        bookCover: "images/booksCovers/1984.jpg",
        bookRating: 4.7,
        bookPrice: 9.99,
        ISBN: 9780451524935,
        publisher: "Signet Classic",
        publicationDate: "06/08/1949",
        pages: 328,
        productDimensions: "4.20(w) x 7.50(h) x 0.83(d)",
        overview: "In a grim future where the Party controls everything and the Thought Police can practically read your mind, Winston Smith is a man in grave danger for the simple reason that his memory still functions. He knows the Party's official image of the world is a fluid fiction and that the Party controls the people by feeding them lies and narrowing their imaginations through a process of bewilderment and brutalization.",
        tableOfContent: ["Part 1", "Part 2", "Part 3", "Appendix"],
    },
    {
        bookTitle: "The Martian",
        bookAuthor: "Andy Weir",
        bookCover: "images/booksCovers/The Martian.jpg",
        bookRating: 4.7,
        bookPrice: 17.00,
        ISBN: 9780553418026,
        publisher: "Broadway Books",
        publicationDate: "10/28/2014",
        pages: 387,
        productDimensions: "5.10(w) x 8.00(h) x 1.10(d)",
        overview: "Six days ago, astronaut Mark Watney became one of the first people to walk on Mars. Now, he's sure he'll be the first person to die there. After a dust storm nearly kills him and forces his crew to evacuate while thinking him dead, Mark finds himself stranded and completely alone with no way to even signal Earth that he's alive.",
        tableOfContent: ["Sol 1", "Sol 6", "Sol 12", "Sol 25", "Sol 37", "Sol 48", "NASA"],
    },
    {
        bookTitle: "Ready Player One",
        bookAuthor: "Ernest Cline",
        bookCover: "images/booksCovers/Ready Player One.jpg",
        bookRating: 4.6,
        bookPrice: 17.00,
        ISBN: 9780307887443,
        publisher: "Broadway Books",
        publicationDate: "06/05/2012",
        pages: 384,
        productDimensions: "5.20(w) x 8.00(h) x 0.90(d)",
        overview: "In the year 2045, reality is an ugly place. The only time Wade Watts really feels alive is when he's jacked into the OASIS, a vast virtual world where most of humanity spends their days. When the eccentric creator of the OASIS dies, he leaves behind a series of fiendish puzzles, based on his obsession with the pop culture of decades past, that will grant the solver his fortune and control of his world.",
        tableOfContent: ["Level One", "Level Two", "Level Three"],
    },
    {
        bookTitle: "Neuromancer",
        bookAuthor: "William Gibson",
        bookCover: "images/booksCovers/Neuromancer.jpg",
        bookRating: 4.5,
        bookPrice: 16.00,
        ISBN: 9780441569595,
        publisher: "Ace",
        publicationDate: "07/01/1984",
        pages: 271,
        productDimensions: "4.10(w) x 6.70(h) x 0.90(d)",
        overview: "The Matrix is a world within the world, a global consensus-hallucination, the representation of every byte of data in cyberspace. Henry Dorsett Case was the sharpest data-thief in the business, until vengeful former employees crippled his nervous system. But now a new and very mysterious employer recruits him for a last-chance run.",
        tableOfContent: ["Part 1: Chiba City Blues", "Part 2: The Shopping Expedition", "Part 3: Midnight in the Rue Jules Verne", "Part 4: The Straylight Run", "Coda: Departure and Arrival"],
    },
    {
        bookTitle: "Foundation",
        bookAuthor: "Isaac Asimov",
        bookCover: "images/booksCovers/Foundation.jpg",
        bookRating: 4.6,
        bookPrice: 16.99,
        ISBN: 9780553293357,
        publisher: "Spectra",
        publicationDate: "10/01/1951",
        pages: 256,
        productDimensions: "4.20(w) x 6.90(h) x 0.75(d)",
        overview: "For twelve thousand years the Galactic Empire has ruled supreme. Now it is dying. But only Hari Seldon, creator of the revolutionary science of psychohistory, can see into the future—to a dark age of ignorance, barbarism, and warfare that will last thirty thousand years. To preserve knowledge and save humankind, Seldon gathers the best minds in the Empire and brings them to a bleak planet at the edge of the galaxy to serve as a beacon of hope for future generations.",
        tableOfContent: ["Part 1: The Psychohistorians", "Part 2: The Encyclopedists", "Part 3: The Mayors", "Part 4: The Traders", "Part 5: The Merchant Princes"],
    },
    {
        bookTitle: "Ender's Game",
        bookAuthor: "Orson Scott Card",
        bookCover: "images/booksCovers/Enders Game.jpg",
        bookRating: 4.7,
        bookPrice: 7.99,
        ISBN: 9780812550702,
        publisher: "Tor Science Fiction",
        publicationDate: "07/15/1994",
        pages: 352,
        productDimensions: "4.10(w) x 6.70(h) x 1.00(d)",
        overview: "In order to develop a secure defense against a hostile alien race's next attack, government agencies breed child geniuses and train them as soldiers. A brilliant young boy, Andrew 'Ender' Wiggin lives with his kind but distant parents, his sadistic brother Peter, and the person he loves more than anyone else, his sister Valentine.",
        tableOfContent: ["Chapter 1: Third", "Chapter 2: Peter", "Chapter 3: Graff", "Chapter 4: Launch", "Chapter 5: Games", "Chapter 6: The Giant's Drink"],
    },
    {
        bookTitle: "Snow Crash",
        bookAuthor: "Neal Stephenson",
        bookCover: "images/booksCovers/Snow Crash.jpg",
        bookRating: 4.4,
        bookPrice: 17.00,
        ISBN: 9780553380958,
        publisher: "Del Rey",
        publicationDate: "05/02/2000",
        pages: 470,
        productDimensions: "5.50(w) x 8.20(h) x 1.00(d)",
        overview: "In reality, Hiro Protagonist delivers pizza for Uncle Enzo's CosoNostra Pizza Inc., but in the Metaverse he's a warrior prince. Plunging headlong into the enigma of a new computer virus that's striking down hackers everywhere, he races along the neon-lit streets on a search-and-destroy mission for the shadowy virtual villain.",
        tableOfContent: ["Chapter 1", "Chapter 2", "Chapter 3", "Chapter 4", "Chapter 5", "Chapter 6"],
    },
    {
        bookTitle: "Hyperion",
        bookAuthor: "Dan Simmons",
        bookCover: "images/booksCovers/Hyperion.jpg",
        bookRating: 4.5,
        bookPrice: 18.00,
        ISBN: 9780553283686,
        publisher: "Spectra",
        publicationDate: "02/01/1990",
        pages: 481,
        productDimensions: "4.20(w) x 6.90(h) x 1.10(d)",
        overview: "On the world called Hyperion, beyond the reach of galactic law, waits a creature called the Shrike. There are those who worship it. There are those who fear it. And there are those who have vowed to destroy it. In the Valley of the Time Tombs, where huge, brooding structures move backward through time, the Shrike waits for them all.",
        tableOfContent: ["The Priest's Tale: The Man Who Cried God", "The Soldier's Tale: The War Lovers", "The Poet's Tale: Hyperion Cantos", "The Scholar's Tale: The River Lethe's Taste is Bitter", "The Detective's Tale: The Long Goodbye", "The Consul's Tale: Remembering Siri"],
    },
];

// Romance Books
var romanceBooks = [
    {
        bookTitle: "Pride and Prejudice",
        bookAuthor: "Jane Austen",
        bookCover: "images/booksCovers/Pride and Prejudice.jpg",
        bookRating: 4.8,
        bookPrice: 9.99,
        ISBN: 9780141439518,
        publisher: "Penguin Classics",
        publicationDate: "01/01/1813",
        pages: 416,
        productDimensions: "5.07(w) x 7.75(h) x 0.93(d)",
        overview: "Few have failed to be charmed by the witty and independent spirit of Elizabeth Bennet in Austen's beloved classic. When Elizabeth meets the arrogant Mr. Darcy, her prejudice against his pride leads to perhaps the most famous love story in English literature.",
        tableOfContent: ["Volume 1", "Volume 2", "Volume 3"],
    },
    {
        bookTitle: "Outlander",
        bookAuthor: "Diana Gabaldon",
        bookCover: "images/booksCovers/Outlander.jpg",
        bookRating: 4.6,
        bookPrice: 18.00,
        ISBN: 9780440212560,
        publisher: "Dell",
        publicationDate: "06/01/1992",
        pages: 850,
        productDimensions: "4.20(w) x 6.90(h) x 1.60(d)",
        overview: "Claire Randall, a former combat nurse, is back from the war and reunited with her husband on a second honeymoon when she walks through a standing stone in one of the ancient stone circles that dot the British Isles. Suddenly she is a Sassenach—an outlander—in a Scotland torn by war and raiding border clans in the year 1743.",
        tableOfContent: ["Part 1: Inverness, 1945", "Part 2: Castle Leoch", "Part 3: On the Road", "Part 4: A Whiff of Brimstone", "Part 5: Lallybroch", "Part 6: The Search", "Part 7: Sanctuary"],
    },
    {
        bookTitle: "Me Before You",
        bookAuthor: "Jojo Moyes",
        bookCover: "images/booksCovers/Me Before You.jpg",
        bookRating: 4.6,
        bookPrice: 16.00,
        ISBN: 9780143124542,
        publisher: "Penguin Books",
        publicationDate: "07/30/2013",
        pages: 400,
        productDimensions: "5.40(w) x 8.40(h) x 0.90(d)",
        overview: "Louisa Clark is an ordinary girl living an exceedingly ordinary life who takes a badly needed job working for ex-Master of the Universe Will Traynor, who is wheelchair bound after an accident. Will has always lived a huge life—big deals, extreme sports, worldwide travel—and now he's pretty sure he cannot live the way he is.",
        tableOfContent: ["Prologue", "Part 1", "Part 2", "Part 3", "Epilogue"],
    },
    {
        bookTitle: "The Fault in Our Stars",
        bookAuthor: "John Green",
        bookCover: "images/booksCovers/The Fault in Our Stars.jpg",
        bookRating: 4.7,
        bookPrice: 14.99,
        ISBN: 9780142424179,
        publisher: "Dutton Books",
        publicationDate: "01/10/2012",
        pages: 318,
        productDimensions: "5.50(w) x 8.25(h) x 0.90(d)",
        overview: "Despite the tumor-shrinking medical miracle that has bought her a few years, Hazel has never been anything but terminal, her final chapter inscribed upon diagnosis. But when a gorgeous plot twist named Augustus Waters suddenly appears at Cancer Kid Support Group, Hazel's story is about to be completely rewritten.",
        tableOfContent: ["Chapter 1", "Chapter 2", "Chapter 3", "Chapter 4", "Chapter 5", "Chapter 6", "Chapter 7", "Chapter 8", "Chapter 9", "Chapter 10"],
    },
    {
        bookTitle: "The Time Traveler's Wife",
        bookAuthor: "Audrey Niffenegger",
        bookCover: "images/booksCovers/The Time Travelers Wife.jpg",
        bookRating: 4.5,
        bookPrice: 16.00,
        ISBN: 9781476764832,
        publisher: "Scribner",
        publicationDate: "05/06/2014",
        pages: 592,
        productDimensions: "5.25(w) x 8.00(h) x 1.40(d)",
        overview: "A funny, poignant tale of love and marriage between a time-traveling librarian and an artist who has known him since she was a child. Their passionate affair is one of intense joy and heartbreaking sadness, spanning decades as they struggle to survive their unusual chronology together.",
        tableOfContent: ["Part 1: The Man out of Time", "Part 2: A Drop of Blood in a Bowl of Milk", "Part 3: A Treatise on Longing"],
    },
    {
        bookTitle: "It Ends with Us",
        bookAuthor: "Colleen Hoover",
        bookCover: "images/booksCovers/It Ends with Us.jpg",
        bookRating: 4.8,
        bookPrice: 16.99,
        ISBN: 9781501110368,
        publisher: "Atria Books",
        publicationDate: "08/02/2016",
        pages: 384,
        productDimensions: "5.31(w) x 8.25(h) x 1.00(d)",
        overview: "Lily hasn't always had it easy, but that's never stopped her from working hard for the life she wants. She's come a long way from the small town where she grew up—she graduated from college, moved to Boston, and started her own business. When she feels a spark with a gorgeous neurosurgeon named Ryle Kincaid, everything in Lily's life seems too good to be true.",
        tableOfContent: ["Part 1", "Part 2", "Part 3", "Part 4"],
    },
    {
        bookTitle: "The Hating Game",
        bookAuthor: "Sally Thorne",
        bookCover: "images/booksCovers/The Hating Game.jpg",
        bookRating: 4.7,
        bookPrice: 15.99,
        ISBN: 9780062439598,
        publisher: "William Morrow Paperbacks",
        publicationDate: "08/09/2016",
        pages: 384,
        productDimensions: "5.31(w) x 8.00(h) x 0.86(d)",
        overview: "Lucy Hutton has always been certain that the nice girl can get the corner office. She's charming and accommodating and prides herself on being loved by everyone. Everyone except Joshua Templeman, the cold, efficient, and ruthless executive who shares her office. Now they're competing for the same promotion, and Lucy refuses to back down.",
        tableOfContent: ["Chapter 1: The Hating Game", "Chapter 2: The Staring Game", "Chapter 3: The Mirror Game", "Chapter 4: The Kissing Game", "Chapter 5: The Dating Game"],
    },
    {
        bookTitle: "The Duke and I",
        bookAuthor: "Julia Quinn",
        bookCover: "images/booksCovers/The Duke and I.jpg",
        bookRating: 4.5,
        bookPrice: 16.99,
        ISBN: 9780063078697,
        publisher: "Avon",
        publicationDate: "01/05/2021",
        pages: 464,
        productDimensions: "5.31(w) x 8.00(h) x 0.75(d)",
        overview: "In the ballrooms and drawing rooms of Regency London, rules abound. From their earliest days, children of aristocrats learn how to address an earl and curtsey before a prince. But the Bridgertons are far from typical. There's only one rule: when it comes to the game of love, no Bridgerton is ever out.",
        tableOfContent: ["Prologue", "Chapter 1", "Chapter 2", "Chapter 3", "Chapter 4", "Chapter 5", "Epilogue"],
    },
];

var allBooksObjects = [
    ...ficBooks.map(book => book),
    ...nonficBooks.flatMap(book => book),
    ...bioBooks.flatMap(book => book),
    ...horrorBooks.flatMap(book => book),
    ...historyBooks.flatMap(book => book),
    ...mysteryThrillerBooks.flatMap(book => book),
    ...mangaBooks.flatMap(book => book),
    ...selfHelpBooks.flatMap(book => book),
    ...scifiBooks.flatMap(book => book),
]

console.log(allBooksObjects);

var allBooksTitles = [
    ...ficBooks.map(book => book.bookTitle),
    ...nonficBooks.map(book => book.bookTitle),
    ...bioBooks.map(book => book.bookTitle),
    ...horrorBooks.map(book => book.bookTitle),
    ...romanceBooks.map(book => book.bookTitle),
    ...mysteryThrillerBooks.map(book => book.bookTitle),
    ...scifiBooks.map(book => book.bookTitle),
    ...selfHelpBooks.map(book => book.bookTitle),
    ...mangaBooks.map(book => book.bookTitle)
]

console.log(allBooksTitles);




