var ficBooks = [
    {
        bookTitle: "Dune",
        bookAuthor: "Frank Herbert",
        bookCover: "images/dune.jpg",
        bookRating: 5,
        bookPrice: 10.99,
        ISBN: 9780441013593,
        publisher: "Penguin Publishing Group",
        publicationDate: "08/02/2005",
        pages: 704,
        productDimensions: "5.84(w) x 8.92(h) x 1.12(d)",
        overview: "A masterpiece of the Science Fiction genre, Dune laid the foundation for many of the epics that followed. Frank Herbert addresses overarching themes of family politics, religion, environment and the all-encompassing temptation of power, all set against the backdrop of a futuristic civilization that, at times, can be unflinchingly prophetic. You will taste the sand in your mouth and soon be hungry for the next installment. • DUNE: PART TWO • THE MAJOR MOTION PICTURE Directed by Denis Villeneuve, screenplay by Denis Villeneuve and Jon Spaihts, based on the novel Dune by Frank Herbert • Starring Timothée Chalamet, Zendaya, Rebecca Ferguson, Josh Brolin, Austin Butler, Florence Pugh, Dave Bautista, Christopher Walken, Stephen McKinley Henderson, Léa Seydoux, with Stellan Skarsgård, with Charlotte Rampling, and Javier Bardem Frank Herbert’s classic masterpiece—a triumph of the imagination and one of the bestselling science fiction novels of all time. Set on the desert planet Arrakis, Dune is the story of Paul Atreides—who would become known as Muad'Dib—and of a great family's ambition to bring to fruition humankind's most ancient and unattainable dream. A stunning blend of adventure and mysticism, environmentalism and politics, Dune won the first Nebula Award, shared the Hugo Award, and formed the basis of what is undoubtedly the grandest epic in science fiction.",
        tableOfContent: ["DuneBook I. Dune", "Book II. Muad'dib", "Book III. The Prophet", "Appendix I: The Ecology of Dune", "Appendix II: The Religion of Dune", "Appendix III: Report on Bene Gesserit", "Motives and Purposes", "Appendix IV: The Almanaken-Ashraf", "(Selected Excerpts of the Noble Houses)"],
    },
    {
        bookTitle: "The Odyssey",
        bookAuthor: "Homer",
        bookCover: "images/the odyssey.jpg",
        bookRating: 5,
        bookPrice: 12,
        ISBN: 9780140268867,
        publisher: "Penguin Classics",
        publicationDate: "11/01/1997",
        pages: 560,
        productDimensions: "5.10(w) x 7.80(h) x 1.10(d)",
        overview: "The Odyssey is one of the greatest works of classical literature, attributed to the ancient Greek poet Homer. It tells the epic tale of Odysseus's journey home after the Trojan War, filled with adventure, danger, and the enduring power of human resilience.",
        tableOfContent: ["Book I: Athena Inspires the Prince", "Book II: Telemachus Sets Sail", "Book III: King Nestor Remembers", "Book IV: The King and Queen of Sparta", "Book V: Odysseus - Nymph and Shipwreck", "Book VI: The Princess and the Stranger"],
    },
    {
        bookTitle: "The Hunger Games",
        bookAuthor: "Suzanne Collins",
        bookCover: "images/The hunger Games.jpg",
        bookRating: 4,
        bookPrice: 6.99,
        ISBN: 9780439023481,
        publisher: "Scholastic Press",
        publicationDate: "09/14/2008",
        pages: 384,
        productDimensions: "5.50(w) x 8.25(h) x 1.00(d)",
        overview: "In a dystopian future, Katniss Everdeen volunteers to take her sister's place in the Hunger Games, a televised fight to the death. Suzanne Collins's gripping novel explores themes of survival, sacrifice, and rebellion.",
        tableOfContent: ["Part I: The Tributes", "Part II: The Games", "Part III: The Victor"],
    },
    {
        bookTitle: "The Girl With The Dragon Tattoo",
        bookAuthor: "Stieg Larsson",
        bookCover: "images/the girl with the dragon tattoo.jpg",
        bookRating: 4,
        bookPrice: 7.99,
        ISBN: 9780307949486,
        publisher: "Vintage Crime/Black Lizard",
        publicationDate: "11/22/2011",
        pages: 672,
        productDimensions: "5.20(w) x 8.00(h) x 1.30(d)",
        overview: "A spellbinding mystery thriller, The Girl With The Dragon Tattoo follows journalist Mikael Blomkvist and hacker Lisbeth Salander as they unravel a decades-old disappearance in Sweden.",
        tableOfContent: ["Prologue", "Part 1: Incentive", "Part 2: Consequence Analysis", "Part 3: Mergers and Acquisitions"],
    },
    {
        bookTitle: "Sunrise on the Reaping (A Hunger Games Novel)",
        bookAuthor: "Suzanne Collins",
        bookCover: "images/booksCovers/Sunrise on the Reaping (A Hunger Games Novel).jpg",
        bookRating: 5,
        bookPrice: 22.39,
        ISBN: 9781546171461        ,
        publisher: "Scholastic, Inc.",
        publicationDate: "03/18/2025",
        pages: 400,
        productDimensions: "5.80(w) x 8.30(h) x 1.50(d)",
        overview: "The Fiftieth Annual Hunger Games are about to begin. Who will be tribute? Who will live and die? Return to Panem for more pulse-pounding action than ever before. Oh, and may the odds be ever in your favor.\n\nThe phenomenal fifth book in the Hunger Games series!\nWhen you’ve been set up to lose everything you love, what is there left to fight for?\n\nAs the day dawns on the fiftieth annual Hunger Games, fear grips the districts of Panem. This year, in honor of the Quarter Quell, twice as many tributes will be taken from their homes.\n\nBack in District 12, Haymitch Abernathy is trying not to think too hard about his chances. All he cares about is making it through the day and being with the girl he loves.\n\nWhen Haymitch’s name is called, he can feel all his dreams break. He’s torn from his family and his love, shuttled to the Capitol with the three other District 12 tributes: a young friend who’s nearly a sister to him, a compulsive oddsmaker, and the most stuck-up girl in town. As the Games begin, Haymitch understands he’s been set up to fail. But there’s something in him that wants to fight . . . and have that fight reverberate far beyond the deadly arena.",
        tableOfContent: ["#", "#", "#", "#"],
    },
    {
        bookTitle: "Great Big Beautiful Life (B&N Exclusive Edition)",
        bookAuthor: "Emily Henry",
        bookCover: "images/booksCovers/Great Big Beautiful Life (B&N Exclusive Edition).jpg",
        bookRating: 5,
        bookPrice: 24.00,
        ISBN: 9780593955628,
        publisher: "Penguin Publishing Group",
        publicationDate: "04/22/2025",
        pages: 384,
        productDimensions: "6.30(w) x 9.20(h) x 1.10(d)",
        overview:"An elusive heiress, a love story and a mystery. Cathartic, romantic, tragic and charming, Emily Henry told her readers this book challenged her like no other. Grab an extra copy — you’ll want to share it with everyone you know.\n\nThis Barnes and Noble Exclusive edition includes a special colorway, beautiful endpapers, and an alternate case color with an exclusive foil-stamped quote.\nTwo writers compete for the chance to tell the larger-than-life story of a woman with more than a couple of plot twists up her sleeve in this dazzling and sweeping new novel from Emily Henry.\n\nAlice Scott is an eternal optimist still dreaming of her big writing break. Hayden Anderson is a Pulitzer-prize winning human thundercloud. And they’re both on balmy Little Crescent Island for the same reason: To write the biography of a woman no one has seen in years--or at least to meet with the octogenarian who claims to be the Margaret Ives. Tragic heiress, former tabloid princess, and daughter of one of the most storied (and scandalous) families of the 20th Century.\n\nWhen Margaret invites them both for a one-month trial period, after which she’ll choose the person who’ll tell her story, there are three things keeping Alice’s head in the game.\n\nOne: Alice genuinely likes people, which means people usually like Alice—and she has a whole month to win the legendary woman over.\n\nTwo: She’s ready for this job and the chance to impress her perennially unimpressed family with a Serious Publication.\n\nThree: Hayden Anderson, who should have no reason to be concerned about losing this book, is glowering at her in a shaken-to-the core way that suggests he sees her as competition.\n\nBut the problem is, Margaret is only giving each of them pieces of her story. Pieces they can’t swap to put together because of an ironclad NDA and an inconvenient yearning pulsing between them every time they’re in the same room.\n\nAnd it’s becoming abundantly clear that their story—just like the tale Margaret’s spinning—could be a mystery, tragedy, or love ballad…depending on who’s telling it.",
        tableOfContent: ["#", "#", "#", "#"],
    },
    {
        bookTitle: "Harry Potter And The Sorcerer's Stone",
        bookAuthor: "J.K. Rowling",
        bookCover: "images/Harry potter and the sorcerer's stone.jpg",
        bookRating: 5,
        bookPrice: 5,
        ISBN: 9780590353427,
        publisher: "Scholastic Inc.",
        publicationDate: "09/01/1998",
        pages: 320,
        productDimensions: "5.50(w) x 8.25(h) x 0.90(d)",
        overview: "The first book in J.K. Rowling's beloved Harry Potter series introduces readers to the magical world of Hogwarts and the young wizard Harry Potter as he discovers his destiny.",
        tableOfContent: ["Chapter 1: The Boy Who Lived", "Chapter 2: The Vanishing Glass", "Chapter 3: The Letters from No One", "Chapter 4: The Keeper of the Keys"],
    },
    {
        bookTitle: "Jurassik Park",
        bookAuthor: "Michael Crichton",
        bookCover: "images/Jurassik Park.jpg",
        bookRating: 4,
        bookPrice: 8,
        ISBN: 9780345538987,
        publisher: "Ballantine Books",
        publicationDate: "11/20/1990",
        pages: 416,
        productDimensions: "5.50(w) x 8.20(h) x 1.10(d)",
        overview: "Michael Crichton's Jurassic Park is a thrilling science fiction novel about a theme park filled with genetically engineered dinosaurs that goes disastrously wrong.",
        tableOfContent: ["Introduction", "Part 1: The Island", "Part 2: The Tour", "Part 3: The Chaos", "Part 4: The Control"],
    },
    {
        bookTitle: "The Hobbit, or There and Back Again",
        bookAuthor: "J.R.R. Tolkien",
        bookCover: "images/The hobbit.jpg",
        bookRating: 4,
        bookPrice: 4.99,
        ISBN: 9780547928227,
        publisher: "Mariner Books",
        publicationDate: "09/21/1937",
        pages: 320,
        productDimensions: "5.30(w) x 8.00(h) x 0.90(d)",
        overview: "J.R.R. Tolkien's classic fantasy novel follows Bilbo Baggins on an epic adventure to reclaim treasure guarded by the dragon Smaug.",
        tableOfContent: ["Chapter 1: An Unexpected Party", "Chapter 2: Roast Mutton", "Chapter 3: A Short Rest", "Chapter 4: Over Hill and Under Hill"],
    },
];

var nonficBooks = [
    {
        bookTitle: "Atomic Habits",
        bookAuthor: "James Clear",
        bookCover: "images/Atomic Habits.jpg",
        bookRating: 4,
        bookPrice: 10,
        ISBN: 9780735211292,
        publisher: "Penguin Publishing Group",
        publicationDate: "10/16/2018",
        pages: 320,
        productDimensions: "6.20(w) x 8.90(h) x 1.20(d)",
        overview: "Thoughtful and easy to understand, James Clear’s Atomic Habits is a must for anyone trying to change their productivity. This simple guide will help create a strong foundation for building good habits and make it easy to say goodbye to bad habits for good.",
        tableOfContent: ["Introduction", "The Fundamentals", "The Four Laws of Behavior Change", "Advanced Tactics"],
    },
    {
        bookTitle: "Freakonomics: A Rogue Economist Explores the Hidden Side of Everything",
        bookAuthor: "Steven D. Levitt",
        bookCover: "images/Freakonomics A Rogue Economist Explores the Hidden Side of Everything.jpg",
        bookRating: 3.8,
        bookPrice: 10,
        ISBN: 9780060731328,
        publisher: "William Morrow",
        publicationDate: "04/12/2005",
        pages: 336,
        productDimensions: "5.31(w) x 8.00(h) x 0.76(d)",
        overview: "Freakonomics explores the hidden side of everything, using economic theory to explain real-world phenomena in surprising ways.",
        tableOfContent: ["What Do Schoolteachers and Sumo Wrestlers Have in Common?", "How Is the Ku Klux Klan Like a Group of Real-Estate Agents?", "Why Do Drug Dealers Still Live with Their Moms?", "Where Have All the Criminals Gone?"],
    },
    {
        bookTitle: "Nudge: Improving Decisions About Health, Wealth, and Happiness",
        bookAuthor: "Richard H. Thaler",
        bookCover: "images/Nudge Improving Decisions About Health, Wealth, and Happiness.jpg",
        bookRating: 3.5,
        bookPrice: 1,
        ISBN: 9780143115267,
        publisher: "Penguin Books",
        publicationDate: "02/24/2009",
        pages: 320,
        productDimensions: "5.50(w) x 8.40(h) x 0.90(d)",
        overview: "Nudge is a groundbreaking book that shows how we can make better decisions about health, wealth, and happiness.",
        tableOfContent: ["Biases and Blunders", "Resisting Temptation", "Choice Architecture", "Saving the Planet"],
    },
    {
        bookTitle: "The Drunkard's Walk: How Randomness Rules Our Lives",
        bookAuthor: "Leonard Mlodinow",
        bookCover: "images/The Drunkard's Walk How Randomness Rules Our Lives.jpg",
        bookRating: 3.9,
        bookPrice: 10,
        ISBN: 9780307275172,
        publisher: "Vintage",
        publicationDate: "05/05/2009",
        pages: 252,
        productDimensions: "5.20(w) x 8.00(h) x 0.70(d)",
        overview: "The Drunkard's Walk explores the role of randomness in our lives and how it influences our decisions and outcomes.",
        tableOfContent: ["The Laws of Randomness", "The Role of Probability", "The Illusion of Patterns", "The Power of Chance"],
    },
    {
        bookTitle: "The Let Them Theory: A Life-Changing Tool That Millions of People Can't Stop Talking About",
        bookAuthor: "Mel Robbins",
        bookCover: "images/The Let Them Theory A Life-Changing Tool That Millions of People Can't Stop Talking About.jpg",
        bookRating: 3.5,
        bookPrice: 10,
        ISBN: 9781401967490,
        publisher: "Hay House Inc.",
        publicationDate: "09/28/2021",
        pages: 240,
        productDimensions: "5.50(w) x 8.50(h) x 0.80(d)",
        overview: "Mel Robbins introduces the 'Let Them Theory,' a simple yet powerful tool for overcoming challenges and achieving personal growth.",
        tableOfContent: ["The Theory", "Applying the Theory", "Overcoming Obstacles", "Achieving Success"],
    },
    {
        bookTitle: "Abundance",
        bookAuthor: "Ezra Klein",
        bookCover: "images/Abundance.jpg",
        bookRating: 3.9,
        bookPrice: 10,
        ISBN: 9781451614213,
        publisher: "Simon & Schuster",
        publicationDate: "02/21/2012",
        pages: 432,
        productDimensions: "6.00(w) x 9.00(h) x 1.20(d)",
        overview: "Abundance explores how technological innovation and human ingenuity are solving the world's biggest challenges.",
        tableOfContent: ["The Future of Innovation", "Solving Global Problems", "The Role of Technology", "A Vision for Tomorrow"],
    },
    {
        bookTitle: "Murdle: Volume 1: 100 Elementary to Impossible Mysteries to Solve Using Logic, Skill, and the Power of Deduction",
        bookAuthor: "G. T. Karber",
        bookCover: "images/murdle vol1.jpg",
        bookRating: 4.8,
        bookPrice: 10,
        ISBN: 9781523518477,
        publisher: "Workman Publishing Company",
        publicationDate: "10/18/2022",
        pages: 288,
        productDimensions: "7.00(w) x 9.00(h) x 0.80(d)",
        overview: "Murdle is a collection of 100 mysteries designed to challenge your logic, deduction, and problem-solving skills.",
        tableOfContent: ["Elementary Mysteries", "Intermediate Mysteries", "Advanced Mysteries", "Impossible Mysteries"],
    },
    {
        bookTitle: "The Body Keeps the Score: Brain, Mind, and Body in the Healing of Trauma",
        bookAuthor: "Bessel van der Kolk M.D.",
        bookCover: "images/The Body Keeps the Score Brain, Mind, and Body in the Healing of Trauma.jpg",
        bookRating: 4.3,
        bookPrice: 10,
        ISBN: 9780143127741,
        publisher: "Penguin Books",
        publicationDate: "09/08/2015",
        pages: 464,
        productDimensions: "5.50(w) x 8.40(h) x 1.10(d)",
        overview: "The Body Keeps the Score is a groundbreaking book on trauma and its impact on the brain, mind, and body.",
        tableOfContent: ["Understanding Trauma", "The Neuroscience of Trauma", "Healing the Mind", "Healing the Body"],
    },
    {
        bookTitle: "The 7 Habits of Highly Effective People",
        bookAuthor: "Stephen R. Covey",
        bookCover: "images/7 Habits of highly effective people.jpg",
        bookRating: 4.6,
        bookPrice: 11.99,
        ISBN: 9780743269513,
        publisher: "Free Press",
        publicationDate: "11/19/2004",
        pages: 381,
        productDimensions: "6.10(w) x 9.20(h) x 1.10(d)",
        overview: "One of the most inspiring and impactful books ever written, *The 7 Habits of Highly Effective People* has captivated readers for over 30 years. Stephen R. Covey presents a holistic, principle-centered approach for solving personal and professional problems. With penetrating insights and practical anecdotes, Covey reveals a step-by-step pathway for living with integrity, fairness, and human dignity—principles that give us the security to adapt to change and the wisdom and power to take advantage of the opportunities that change creates.",
        tableOfContent: [
            "Part One: Paradigms and Principles",
            "Part Two: Private Victory",
            "Part Three: Public Victory",
            "Part Four: Renewal"
        ]
    }
];

var bioBooks = [
    {
        bookTitle: "Steve Jobs",
        bookAuthor: "Walter Isaacson",
        bookCover: "images/steve_jobs.jpg",
        bookRating: 5,
        bookPrice: 10,
        ISBN: 9781982176860,
        publisher: "Simon & Schuster",
        publicationDate: "10/05/2021",
        pages: 672,
        productDimensions: "9.10(w) x 6.00(h) x 1.70(d)",
        overview: "Based on more than forty interviews with Steve Jobs conducted over two years—as well as interviews with more than 100 family members, friends, adversaries, competitors, and colleagues—Walter Isaacson has written a riveting story of the roller-coaster life and searingly intense personality of a creative entrepreneur whose passion for perfection and ferocious drive revolutionized six industries.",
        tableOfContent: ["Characters xiii", "Introduction: How This Book Came to Be xvii", "Chapter 1 Childhood: Abandoned and Chosen 1", "Chapter 2 Odd Couple: The Two Steves 21", "Chapter 3 The Dropout: Turn On, Tune In 31", "Chapter 4 Atari and India: Zen and the Art of Game Design 42"],
    },
    {
        bookTitle: "American Prometheus: The Triumph and Tragedy of J. Robert Oppenheimer",
        bookAuthor: "Kai Bird",
        bookCover: "images/American Prometheus The Triumph and Tragedy of J. Robert Oppenheimer.jpg",
        bookRating: 4.3,
        bookPrice: 10,
        ISBN: 9780375726262,
        publisher: "Vintage",
        publicationDate: "04/11/2006",
        pages: 784,
        productDimensions: "6.10(w) x 9.20(h) x 1.50(d)",
        overview: "A biography of J. Robert Oppenheimer, the father of the atomic bomb, exploring his life, achievements, and the moral dilemmas he faced.",
        tableOfContent: ["Prologue", "Part 1: The Early Years", "Part 2: The Manhattan Project", "Part 3: The Fallout"],
    },
    {
        bookTitle: "Mao: The Unknown Story",
        bookAuthor: "Jung Chang",
        bookCover: "images/Mao The Unknown Story.jpg",
        bookRating: 5,
        bookPrice: 10,
        ISBN: 9780679746324,
        publisher: "Anchor",
        publicationDate: "06/06/2006",
        pages: 864,
        productDimensions: "6.10(w) x 9.20(h) x 1.80(d)",
        overview: "A groundbreaking biography of Mao Zedong, revealing the untold story of his life and the devastating impact of his rule on China.",
        tableOfContent: ["Introduction", "Part 1: The Rise of Mao", "Part 2: The Great Leap Forward", "Part 3: The Cultural Revolution"],
    },
    {
        bookTitle: "Einstein: His Life and Universe",
        bookAuthor: "Walter Isaacson",
        bookCover: "images/Einstein His Life and Universe.jpg",
        bookRating: 4.1,
        bookPrice: 10,
        ISBN: 9780743264747,
        publisher: "Simon & Schuster",
        publicationDate: "04/10/2007",
        pages: 704,
        productDimensions: "6.10(w) x 9.20(h) x 1.50(d)",
        overview: "A comprehensive biography of Albert Einstein, exploring his scientific achievements and personal life.",
        tableOfContent: ["Prologue", "Chapter 1: The Early Years", "Chapter 2: The Miracle Year", "Chapter 3: Relativity", "Chapter 4: The Later Years"],
    },
    {
        bookTitle: "Benjamin Franklin: An American Life",
        bookAuthor: "Walter Isaacson",
        bookCover: "images/Benjamin Franklin An American Life.jpg",
        bookRating: 4.1,
        bookPrice: 10,
        ISBN: 9780743258074,
        publisher: "Simon & Schuster",
        publicationDate: "07/01/2004",
        pages: 608,
        productDimensions: "6.10(w) x 9.20(h) x 1.40(d)",
        overview: "A biography of Benjamin Franklin, exploring his life as a scientist, inventor, diplomat, and one of America's founding fathers.",
        tableOfContent: ["Introduction", "Chapter 1: The Young Franklin", "Chapter 2: The Inventor", "Chapter 3: The Diplomat", "Chapter 4: The Founding Father"],
    },
    {
        bookTitle: "Galileo's Daughter: A Historical Memoir of Science, Faith, and Love",
        bookAuthor: "Dava Sobel",
        bookCover: "images/Galileo's Daughter A Historical Memoir of Science, Faith, and Love.jpg",
        bookRating: 3.7,
        bookPrice: 10,
        ISBN: 9780140280555,
        publisher: "Penguin Books",
        publicationDate: "09/05/2000",
        pages: 432,
        productDimensions: "5.50(w) x 8.40(h) x 1.10(d)",
        overview: "A historical memoir exploring the relationship between Galileo Galilei and his daughter, Maria Celeste, set against the backdrop of the scientific revolution.",
        tableOfContent: ["Prologue", "Chapter 1: The Early Years", "Chapter 2: The Trial", "Chapter 3: The Letters", "Chapter 4: The Legacy"],
    },
    {
        bookTitle: "John Adams",
        bookAuthor: "David McCullough",
        bookCover: "images/john adams.jpg",
        bookRating: 4.4,
        bookPrice: 10,
        ISBN: 9780743223133,
        publisher: "Simon & Schuster",
        publicationDate: "05/22/2001",
        pages: 752,
        productDimensions: "6.10(w) x 9.20(h) x 1.60(d)",
        overview: "A biography of John Adams, the second president of the United States, exploring his role in the American Revolution and the founding of the nation.",
        tableOfContent: ["Introduction", "Chapter 1: The Early Years", "Chapter 2: The Revolution", "Chapter 3: The Presidency", "Chapter 4: The Legacy"],
    },
    {
        bookTitle: "The Autobiography of Malcolm X",
        bookAuthor: "Malcolm X",
        bookCover: "images/The Autobiography of Malcolm X.jpg",
        bookRating: 4.4,
        bookPrice: 10,
        ISBN: 9780345350688,
        publisher: "Ballantine Books",
        publicationDate: "10/12/1987",
        pages: 460,
        productDimensions: "5.50(w) x 8.40(h) x 1.10(d)",
        overview: "The autobiography of Malcolm X, chronicling his journey from a troubled youth to a prominent civil rights leader.",
        tableOfContent: ["Introduction", "Chapter 1: The Early Years", "Chapter 2: The Nation of Islam", "Chapter 3: The Pilgrimage", "Chapter 4: The Legacy"],
    },
    {
        bookTitle: "Alexander Hamilton",
        bookAuthor: "Ron Chernow",
        bookCover: "images/Alexander Hamilton.jpg",
        bookRating: 4.2,
        bookPrice: 10,
        ISBN: 9780143034759,
        publisher: "Penguin Books",
        publicationDate: "04/26/2005",
        pages: 832,
        productDimensions: "6.10(w) x 9.20(h) x 1.70(d)",
        overview: "A biography of Alexander Hamilton, exploring his role as a founding father of the United States and his contributions to the nation's financial system.",
        tableOfContent: ["Introduction", "Chapter 1: The Early Years", "Chapter 2: The Revolutionary War", "Chapter 3: The Federalist Papers", "Chapter 4: The Legacy"],
    },
    {
        bookTitle: "The Da Vinci Code",
        bookAuthor: "Dan Brown",
        bookCover: "images/The Da Vinci Code.jpg",
        bookRating: 4.5,
        bookPrice: 9.99,
        ISBN: 9780307474278,
        publisher: "Anchor",
        publicationDate: "03/31/2009",
        pages: 489,
        productDimensions: "5.20(w) x 8.00(h) x 1.10(d)",
        overview: "THE #1 WORLDWIDE BESTSELLING PHENOMENON, WITH MORE THAN 85 MILLION COPIES SOLD. “Blockbuster perfection . . . a gleefully erudite suspense novel.” —The New York Times. “A pulse-quickening, brain-teasing adventure.” —People. While in Paris, Harvard symbologist Robert Langdon is awakened by a phone call in the dead of the night. The elderly curator of the Louvre has been murdered inside the museum, his body covered in baffling symbols. As Langdon and gifted French cryptologist Sophie Neveu sort through the bizarre riddles, they are stunned to discover a trail of clues hidden in the works of Leonardo da Vinci—clues visible for all to see and yet ingeniously disguised by the painter. Even more startling, the late curator was involved in the Priory of Sion, a secret society whose members included Sir Isaac Newton, Victor Hugo, and Da Vinci, and he guarded a breathtaking historical secret. Unless Langdon and Neveu can decipher the labyrinthine puzzle—while avoiding the faceless adversary who shadows their every move—the explosive, ancient truth will be lost forever.",
        tableOfContent: ["Prologue", "Chapter 1: The Louvre", "Chapter 2: The Cryptex", "Chapter 3: The Priory of Sion", "Chapter 4: The Truth Revealed"]
    }
];
var horrorBooks = [
    {
        bookTitle: "Never Flinch: A Novel",
        bookAuthor: "Stephen King",
        bookCover: "images/booksCovers/Never Flinch A Novel.jpg",
        bookRating: 5,
        bookPrice: 22.40,
        ISBN: 9781668089330,
        publisher: "Scribner",
        publicationDate: "05/27/2025",
        pages: 448,
        productDimensions: "6.12(w) x 9.25(h) x 1.50(d)",
        overview: "An elusive heiress, a love story and a mystery. Cathartic, romantic, tragic and charming, Emily Henry told her readers this book challenged her like no other. Grab an extra copy — you’ll want to share it with everyone you know.\n\nThis Barnes and Noble Exclusive edition includes a special colorway, beautiful endpapers, and an alternate case color with an exclusive foil-stamped quote.\nTwo writers compete for the chance to tell the larger-than-life story of a woman with more than a couple of plot twists up her sleeve in this dazzling and sweeping new novel from Emily Henry.",
        tableOfContent: ["#", "#", "#", "#"],
    },
    {
        bookTitle: "It",
        bookAuthor: "Stephen King",
        bookCover: "images/booksCovers/It.jpg",
        bookRating: 5,
        bookPrice: 18.99,
        ISBN: 9780450411434,
        publisher: "Viking",
        publicationDate: "09/15/1986",
        pages: 1138,
        productDimensions: "6.10(w) x 9.20(h) x 2.50(d)",
        overview: "A group of children face an ancient, shape-shifting evil that emerges every 27 years to prey on the town of Derry, Maine. Decades later, they reunite to confront their fears and destroy the monster once and for all.",
        tableOfContent: ["Part 1: The Shadow Before", "Part 2: June of 1958", "Part 3: Grownups", "Part 4: July of 1958", "Part 5: The Ritual of Chüd"],
    },
    {
        bookTitle: "The Haunting of Hill House",
        bookAuthor: "Shirley Jackson",
        bookCover: "images/booksCovers/The Haunting of Hill House.jpg",
        bookRating: 4.8,
        bookPrice: 14.99,
        ISBN: 9780143039983,
        publisher: "Penguin Classics",
        publicationDate: "10/16/1959",
        pages: 246,
        productDimensions: "5.50(w) x 8.40(h) x 0.70(d)",
        overview: "Four seekers arrive at a notoriously unfriendly mansion called Hill House. At first, their stay seems destined to be merely a spooky encounter, but Hill House is gathering its powers—and soon it will choose one of them to make its own.",
        tableOfContent: ["Chapter 1", "Chapter 2", "Chapter 3", "Chapter 4", "Chapter 5"],
    },
    {
        bookTitle: "Dracula",
        bookAuthor: "Bram Stoker",
        bookCover: "images/booksCovers/Dracula.jpg",
        bookRating: 4.7,
        bookPrice: 12.50,
        ISBN: 9780141439846,
        publisher: "Penguin Classics",
        publicationDate: "05/26/1897",
        pages: 488,
        productDimensions: "5.10(w) x 7.80(h) x 1.10(d)",
        overview: "The classic Gothic horror novel that introduced Count Dracula to the world. A tale of suspense, terror, and the eternal struggle between good and evil.",
        tableOfContent: ["Jonathan Harker's Journal", "Mina Murray's Journal", "Dr. Seward's Diary", "The Hunt for Dracula"],
    },
    {
        bookTitle: "The Shining",
        bookAuthor: "Stephen King",
        bookCover: "images/booksCovers/The Shining.jpg",
        bookRating: 5,
        bookPrice: 16.99,
        ISBN: 9780307743657,
        publisher: "Anchor",
        publicationDate: "01/28/1977",
        pages: 659,
        productDimensions: "5.50(w) x 8.20(h) x 1.50(d)",
        overview: "Jack Torrance becomes the winter caretaker at the isolated Overlook Hotel in Colorado, hoping to cure his writer's block. But as the harsh winter sets in, the hotel's dark secrets begin to surface, and Jack's sanity unravels.",
        tableOfContent: ["Part 1: Prefatory Matters", "Part 2: Closing Day", "Part 3: The Wasps' Nest", "Part 4: Snowbound", "Part 5: Matters of Life and Death"],
    },
    {
        bookTitle: "Pet Sematary",
        bookAuthor: "Stephen King",
        bookCover: "images/booksCovers/Pet Sematary.jpg",
        bookRating: 4.9,
        bookPrice: 15.99,
        ISBN: 9780743412285,
        publisher: "Pocket Books",
        publicationDate: "11/14/1983",
        pages: 416,
        productDimensions: "5.50(w) x 8.25(h) x 1.00(d)",
        overview: "When Louis Creed moves his family to a rural town, he discovers a mysterious burial ground that brings the dead back to life—with horrifying consequences.",
        tableOfContent: ["Part 1: The Pet Sematary", "Part 2: The Micmac Burial Ground", "Part 3: The Return"],
    },
    {
        bookTitle: "Frankenstein",
        bookAuthor: "Mary Shelley",
        bookCover: "images/booksCovers/Frankenstein.jpg",
        bookRating: 4.8,
        bookPrice: 10.99,
        ISBN: 9780486282114,
        publisher: "Dover Publications",
        publicationDate: "01/01/1818",
        pages: 166,
        productDimensions: "5.00(w) x 8.00(h) x 0.50(d)",
        overview: "A classic tale of horror and science fiction, Frankenstein tells the story of Victor Frankenstein and the monstrous creation that haunts him.",
        tableOfContent: ["Letter 1", "Chapter 1", "Chapter 2", "Chapter 3", "Chapter 4"],
    },
    {
        bookTitle: "The Exorcist",
        bookAuthor: "William Peter Blatty",
        bookCover: "images/booksCovers/The Exorcist.jpg",
        bookRating: 4.7,
        bookPrice: 14.99,
        ISBN: 9780061007224,
        publisher: "HarperTorch",
        publicationDate: "10/01/1971",
        pages: 400,
        productDimensions: "5.30(w) x 8.00(h) x 1.00(d)",
        overview: "A chilling story of demonic possession and the battle between good and evil, The Exorcist is a masterpiece of horror fiction.",
        tableOfContent: ["Part 1: The Beginning", "Part 2: The Possession", "Part 3: The Exorcism"],
    },
    {
        bookTitle: "Bird Box",
        bookAuthor: "Josh Malerman",
        bookCover: "images/booksCovers/Bird Box.jpg",
        bookRating: 4.5,
        bookPrice: 13.99,
        ISBN: 9780062259660,
        publisher: "Ecco",
        publicationDate: "05/13/2014",
        pages: 272,
        productDimensions: "5.50(w) x 8.25(h) x 0.80(d)",
        overview: "In a world where unseen creatures drive people to madness and death, a mother and her children must navigate a treacherous journey blindfolded to survive.",
        tableOfContent: ["Chapter 1", "Chapter 2", "Chapter 3", "Chapter 4", "Chapter 5"],
    },
];

var allBooksObjects = [
    ...ficBooks.map(book => book),
    ...nonficBooks.flatMap(book => book),
    ...bioBooks.flatMap(book => book),
    ...horrorBooks.flatMap(book => book),
]

console.log(allBooksObjects);

var allBooksTitles = [
    ...ficBooks.map(book => book.bookTitle),
    ...nonficBooks.map(book => book.bookTitle),
    ...bioBooks.map(book => book.bookTitle),
    ...horrorBooks.map(book => book.bookTitle)
];

