var allAuthors = [
    {
        name: "James Clear",
        dob : "1986",
        dob: "Hamilton, OH",
        shortBio:"James Clear is a writer and speaker focused on habits, decision making, and continuous improvement. He is the author of the #1 New York Times bestseller, Atomic Habits. The book has sold over 20 million copies worldwide and has been translated into more than 60 languages. Clear is a regular speaker at Fortune 500 companies and his work has been featured in places like Time magazine, the New York Times, the Wall Street Journal and on CBS This Morning. His popular 3-2-1 email newsletter is sent out each week to more than 3 million subscribers.",
        pic:"images/authorsPics/James Clear.jpg",
    },
    {
        name: "Walter Isaacson",
        dob: "May 20, 1952",
        pob: "New Orleans, LA",
        shortBio: "Walter Isaacson is the bestselling author of biographies of Jennifer Doudna, Leonardo da Vinci, Steve Jobs, Benjamin Franklin, and Albert Einstein. He is a professor of history at Tulane and was CEO of the Aspen Institute, chair of CNN, and editor of Time. He was awarded the National Humanities Medal in 2023. Visit him at Isaacson.Tulane.edu.",
        pic: "images/authorsPics/walter isaacson.jpg",
    },
    {
        name: "Frank Herbert",
        dob: "October 8, 1920",
        pob: "Tacoma, Washington",
        shortBio: "Frank Herbert is the bestselling author of the Dune saga. He worked a wide variety of jobs—including TV cameraman, radio commentator, oyster diver, jungle survival instructor, lay analyst, creative writing teacher, reporter, and editor—before becoming a full-time writer. His Dune series is considered one of the monuments of modern science fiction. He died in 1986.",
        pic: "images/authorsPics/Frank Herbert.jpeg",
    },
    {
        name: "Homer",
        dob: "8th Century BC",
        pob: "Ancient Greece",
        shortBio: "Homer is the legendary ancient Greek poet traditionally said to be the author of the epic poems The Iliad and The Odyssey, which have had an enormous influence on Western literature and culture.",
        pic: "images/authorsPics/Homer.jpeg",
    },
    {
        name: "Suzanne Collins",
        dob: "August 10, 1962",
        pob: "Hartford, Connecticut",
        shortBio: "Suzanne Collins is the author of the worldwide bestselling Hunger Games trilogy. She began her career as a writer for children's television and has received numerous awards for her work.",
        pic: "images/authorsPics/Suzanne Collins.jpeg",
    },
    {
        name: "Stieg Larsson",
        dob: "August 15, 1954",
        pob: "Skelleftehamn, Sweden",
        shortBio: "Stieg Larsson was a Swedish journalist and writer, best known for his Millennium series, which includes The Girl with the Dragon Tattoo. He passed away in 2004 before the series gained international acclaim.",
        pic: "images/authorsPics/Stieg Larsson.jpeg",
    },
    {
        name: "J.K. Rowling",
        dob: "July 31, 1965",
        pob: "Yate, Gloucestershire, England",
        shortBio: "J.K. Rowling is the author of the Harry Potter series, one of the most successful book franchises in history. She has also written novels for adults under the pen name Robert Galbraith.",
        pic: "images/authorsPics/J.K. Rowling.jpg",
    },
    {
        name: "Michael Crichton",
        dob: "October 23, 1942",
        pob: "Chicago, Illinois",
        shortBio: "Michael Crichton was an American author and filmmaker, best known for his science fiction and thriller novels, including Jurassic Park. Many of his works have been adapted into successful films.",
        pic: "images/authorsPics/MichaelCrichton.jpg",
    },
    {
        name: "J.R.R. Tolkien",
        dob: "January 3, 1892",
        pob: "Bloemfontein, Orange Free State",
        shortBio: "J.R.R. Tolkien was an English writer, poet, and academic, best known for his high-fantasy works The Hobbit and The Lord of the Rings. He is widely regarded as the father of modern fantasy literature.",
        pic: "images/authorsPics/J.R.R. Tolkien.jpg",
    },
    {
        name: "Mel Robbins",
        dob: "October 6, 1968",
        pob: "Kansas City, Missouri, USA",
        shortBio: "Mel Robbins is a motivational speaker, author, and former CNN legal analyst. She is best known for her book 'The 5 Second Rule' and her work on personal development and productivity.",
        pic: "images/authorsPics/Mel Robbins.jpeg",
    },
    {
        name: "Ezra Klein",
        dob: "May 9, 1984",
        pob: "Irvine, California, USA",
        shortBio: "Ezra Klein is an American journalist, political analyst, and author. He is the co-founder of Vox and the author of 'Why We're Polarized.' He is known for his work on politics, policy, and media.",
        pic: "images/authorsPics/Ezra Klein.jpg",
    },
    {
        name: "G. T. Karber",
        dob: "Unknown",
        pob: "USA",
        shortBio: "G. T. Karber is an author and puzzle designer known for his book 'Murdle: Volume 1,' which challenges readers with mysteries and puzzles that test logic and deduction skills.",
        pic: "images/authorsPics/G. T. Karber.jpg",
    },
    {
        name: "Bessel van der Kolk M.D.",
        dob: "July 23, 1943",
        pob: "The Hague, Netherlands",
        shortBio: "Bessel van der Kolk is a psychiatrist, researcher, and author specializing in post-traumatic stress disorder (PTSD). He is best known for his book 'The Body Keeps the Score,' which explores the impact of trauma on the brain and body.",
        pic: "images/authorsPics/Bessel van der Kolk M.D..jpg",
    },
    {
        name: "Steven D. Levitt",
        dob: "May 29, 1967",
        pob: "New Orleans, Louisiana, USA",
        shortBio: "Steven D. Levitt is an economist and professor at the University of Chicago. He is the co-author of the bestselling book 'Freakonomics,' which explores the hidden side of everyday life through economic theory.",
        pic: "images/authorsPics/Steven D. Levitt.jpg",
    },
    {
        name: "Richard H. Thaler",
        dob: "September 12, 1945",
        pob: "East Orange, New Jersey, USA",
        shortBio: "Richard H. Thaler is an economist and professor at the University of Chicago. He is a pioneer in behavioral economics and the co-author of 'Nudge,' which explores how small changes can influence decision-making.",
        pic: "images/authorsPics/Richard H. Thaler.jpg",
    },
    {
        name: "Leonard Mlodinow",
        dob: "November 26, 1954",
        pob: "Chicago, Illinois, USA",
        shortBio: "Leonard Mlodinow is a physicist, author, and screenwriter. He is known for his books on science and mathematics, including 'The Drunkard's Walk,' which explores the role of randomness in our lives.",
        pic: "images/authorsPics/Leonard Mlodinow.jpg",
    },
    {
        name: "Dan Brown",
        dob: "June 22, 1964",
        pob: "Exeter, New Hampshire, USA",
        shortBio: "Dan Brown is an American author best known for his thriller novels, including the worldwide bestseller 'The Da Vinci Code.' His works often explore themes of cryptography, art, and religion, blending historical and scientific elements into gripping narratives.",
        pic: "images/authorsPics/Dan Brown.jpeg",
    },
    {
        name: "Stephen R. Covey",
        dob: "October 24, 1932",
        pob: "Salt Lake City, Utah, USA",
        shortBio: "Stephen R. Covey was an American educator, author, businessman, and keynote speaker. He is best known for his book 'The 7 Habits of Highly Effective People,' which has sold millions of copies worldwide and remains a cornerstone of personal development literature.",
        pic: "images/authorsPics/Stephen R. Covey.jpg",
    },
    {
        name: "Jung Chang",
        dob: "March 25, 1952",
        pob: "Yibin, Sichuan, China",
        shortBio: "Jung Chang is a Chinese-born British writer and historian, best known for her internationally acclaimed book 'Wild Swans: Three Daughters of China' and the biography 'Mao: The Unknown Story,' co-authored with her husband, Jon Halliday. Her works provide deep insights into Chinese history and culture.",
        pic: "images/authorsPics/Jung Chang.jpeg",
    },
    {
        name: "Kai Bird",
        dob: "September 2, 1951",
        pob: "Eugene, Oregon, USA",
        shortBio: "Kai Bird is an American author and historian, best known for his biographies and works on American foreign policy. He is the co-author of the Pulitzer Prize-winning biography 'American Prometheus: The Triumph and Tragedy of J. Robert Oppenheimer,' which explores the life of the father of the atomic bomb.",
        pic: "images/authorsPics/Kai Bird.jpeg",
    },
    {
        name: "Dava Sobel",
        dob: "June 15, 1947",
        pob: "The Bronx, New York City, USA",
        shortBio: "Dava Sobel is an American writer and former science reporter. She is best known for her books 'Longitude,' which tells the story of the invention of the marine chronometer, and 'Galileo's Daughter,' a historical memoir exploring the life of Galileo Galilei and his relationship with his daughter Maria Celeste.",
        pic: "images/authorsPics/Dava Sobel.jpeg",
    },
    {
        name: "David McCullough",
        dob: "July 7, 1933",
        pob: "Pittsburgh, Pennsylvania, USA",
        shortBio: "David McCullough was an American author, narrator, and historian, widely regarded as one of the greatest popular historians of his time. He is best known for his Pulitzer Prize-winning biographies 'Truman' and 'John Adams,' as well as his works on American history, including '1776' and 'The Wright Brothers.'",
        pic: "images/authorsPics/David McCullough.jpeg",
    },
    {
        name: "Malcolm X",
        dob: "May 19, 1925",
        pob: "Omaha, Nebraska, USA",
        shortBio: "Malcolm X was an African-American Muslim minister, human rights activist, and prominent figure during the civil rights movement. He is best known for his autobiography, 'The Autobiography of Malcolm X,' which chronicles his journey from a troubled youth to a prominent leader advocating for Black empowerment and justice.",
        pic: "images/authorsPics/Malcolm X.jpeg",
    },
    {
        name: "Ron Chernow",
        dob: "March 3, 1949",
        pob: "New York City, New York, USA",
        shortBio: "Ron Chernow is an American historian, biographer, and journalist. He is best known for his biographies of historical figures, including 'Alexander Hamilton,' which inspired the hit Broadway musical, and 'Washington: A Life,' which won the Pulitzer Prize for Biography. His works are celebrated for their depth and narrative style.",
        pic: "images/authorsPics/Ron Chernow.jpeg",
    },
    {
        name: "Emily Henry",
        dob: "May 17, 1991",
        pob: "United States",
        shortBio: "Emily Henry is the #1 New York Times bestselling author of Funny Story, Happy Place, Book Lovers, People We Meet on Vacation, and Beach Read. She studied creative writing at Hope College, and now spends most of her time in Cincinnati, Ohio, and the part of Kentucky just beneath it. Find her on Instagram @emilyhenrywrites.",
        pic: "images/authorsPics/Emily Henry.jpeg",
    },
    {
        name: "Stephen King",
        dob: "September 21, 1947",
        pob: "Portland, Maine",
        shortBio: "Emily Henry is the #1 New York Times bestselling author of Funny Story, Happy Place, Book Lovers, People We Meet on Vacation, and Beach Read. She studied creative writing at Hope College, and now spends most of her time in Cincinnati, Ohio, and the part of Kentucky just beneath it. Find her on Instagram @emilyhenrywrites.",
        pic: "images/authorsPics/StephenKing.jpeg",
    },
    {
        name: "Shirley Jackson",
        dob: "December 14, 1916",
        pob: "San Francisco, California, USA",
        shortBio: "Shirley Jackson was an American writer known for her works of horror and mystery. Her novel 'The Haunting of Hill House' is considered one of the best ghost stories ever written. She also authored the famous short story 'The Lottery.'",
        pic: "images/authorsPics/Shirley Jackson.jpg",
    },
    {
        name: "Bram Stoker",
        dob: "November 8, 1847",
        pob: "Clontarf, Dublin, Ireland",
        shortBio: "Bram Stoker was an Irish author best known for his Gothic horror novel 'Dracula,' which introduced the iconic character Count Dracula and has influenced countless works of fiction and film.",
        pic: "images/authorsPics/Bram Stoker.jpg",
    },
    {
        name: "Mary Shelley",
        dob: "August 30, 1797",
        pob: "London, England",
        shortBio: "Mary Shelley was an English novelist best known for her Gothic novel 'Frankenstein; or, The Modern Prometheus.' She is considered one of the pioneers of science fiction and horror literature.",
        pic: "images/authorsPics/Mary Shelley.jpg",
    },
    {
        name: "William Peter Blatty",
        dob: "January 7, 1928",
        pob: "New York City, New York, USA",
        shortBio: "William Peter Blatty was an American writer and filmmaker, best known for his horror novel 'The Exorcist,' which became a cultural phenomenon and was adapted into an iconic film.",
        pic: "images/authorsPics/William Peter Blatty.jpg",
    },
    {
        name: "Josh Malerman",
        dob: "July 24, 1975",
        pob: "Southfield, Michigan, USA",
        shortBio: "Josh Malerman is an American author and musician, best known for his debut novel 'Bird Box,' a post-apocalyptic horror story that was adapted into a successful Netflix film.",
        pic: "images/authorsPics/Josh Malerman.jpg",
    },
];